using System;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        // Outer BoxContainer margin (4) on each side; keeps the grid's max width inside the panel.
        private const float OptionsWidthPadding = 8f;

        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IVoteManager _voteManager = default!;
        [Dependency] private readonly IEntityNetworkManager _net = default!;

        private readonly VoteManager.ActiveVote _vote;
        private readonly Button[] _voteButtons;
        private readonly NetEntity? _targetEntity;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSystem;

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.Visible = true;
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
            }

            Modulate = Color.White.WithAlpha(0.75f);

            _voteButtons = new Button[vote.Entries.Length];
            var group = new ButtonGroup();

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Group = group,
                    // Fill the uniform grid cell so short options match the widest one
                    // instead of leaving the text hugging one edge.
                    HorizontalExpand = true,
                    TextAlign = Label.AlignMode.Center,
                };
                _voteButtons[i] = button;
                VoteOptionsContainer.AddChild(button);
                var i1 = i;
                button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }
        }

        public void UpdateData()
        {
            VoteTitle.SetMessage(FormattedMessage.FromUnformatted(_vote.Title));
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var entry = _vote.Entries[i];
                if (_vote.DisplayVotes)
                {
                    _voteButtons[i].Text = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes));
                }
                else
                {
                    _voteButtons[i].Text = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text));
                }

                if (_vote.OurVote == i)
                    _voteButtons[i].Pressed = true;
            }
        }

        protected override Vector2 MeasureOverride(Vector2 availableSize)
        {
            // Whatever container hosts us (the wide in-round HUD, or the lobby's narrow
            // left-hand column) may offer less width than our own MaxWidth. Recompute the
            // grid's target width from what's actually available every measure pass, so it
            // never lays out more columns than fit — the layout system clamps our own final
            // size down to that same availableSize regardless (see MeasureCore), and if the
            // grid had already committed to a wider column layout it gets squeezed instead of
            // just showing fewer, correctly-sized columns.
            var available = float.IsFinite(availableSize.X) ? availableSize.X : MaxWidth;
            var gridMaxWidth = MathF.Max(1f, MathF.Min(MaxWidth, available) - OptionsWidthPadding);
            VoteOptionsContainer.MaxGridWidth = gridMaxWidth;

            return base.MeasureOverride(availableSize);
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // Logger.Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            TimeLeftBar.Value = Math.Min(1, (float) ((curTime.TotalSeconds - _vote.StartTime.TotalSeconds) /
                                                     (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

            TimeLeftText.Text = $"{timeLeft:m\\:ss}";
        }
    }
}
