using System.Linq;
using System.Numerics;
using Content.Client._Duty.Administration;
using Content.Client.Administration.Managers;
using Content.Client.Administration.UI.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminMenuWindow : DefaultWindow
{
    public event Action? OnDisposed;

    // _Duty: окно знает, какие кнопки доступны, поэтому пустые вкладки прячем, а по командам можно искать
    private readonly IClientAdminManager _admin;

    public AdminMenuWindow()
    {
        _admin = IoCManager.Resolve<IClientAdminManager>();

        MinSize = new Vector2(700, 380);
        SetSize = new Vector2(900, 560); // _Duty: окно побольше, кнопки не теснятся
        Title = Loc.GetString("admin-menu-title");
        RobustXamlLoader.Load(this);
        MasterTabContainer.SetTabTitle((int) TabIndex.Admin, Loc.GetString("admin-menu-admin-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Adminbus, Loc.GetString("admin-menu-adminbus-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Atmos, Loc.GetString("admin-menu-atmos-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Round, Loc.GetString("admin-menu-round-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Server, Loc.GetString("admin-menu-server-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.PanicBunker, Loc.GetString("admin-menu-panic-bunker-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Players, Loc.GetString("admin-menu-players-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Objects, Loc.GetString("admin-menu-objects-tab"));
        MasterTabContainer.OnTabChanged += OnTabChanged;

        // _Duty-start: поиск и скрытие пустых вкладок
        SearchBar.OnTextChanged += args => RunSearch(args.Text);
        _admin.AdminStatusUpdated += RefreshTabs;
        OnOpen += RefreshTabs;
        // _Duty-end
    }

    private void OnTabChanged(int tabIndex)
    {
        var tabEnum = (TabIndex)tabIndex;
        if (tabEnum == TabIndex.Objects)
            ObjectsTabControl.RefreshObjectList();
    }

    // _Duty-start: скрываем вкладки, где не осталось ни одной доступной кнопки команды
    private void RefreshTabs()
    {
        for (var i = 0; i < MasterTabContainer.ChildCount; i++)
        {
            var tab = (TabIndex) i;

            // Игроки и Объекты показываем всегда: там списки, а не кнопки
            if (tab is TabIndex.Players or TabIndex.Objects)
                continue;

            var control = MasterTabContainer.GetChild(i);
            var buttons = CommandButtons(control).ToList();
            var visible = buttons.Count == 0 || buttons.Any(b => b.IsAllowed);

            // «АдминАбуз» содержит и кнопки без команд (спавн): их открывает право спавна
            if (tab == TabIndex.Adminbus && _admin.CanAdminPlace())
                visible = true;

            MasterTabContainer.SetTabVisible(i, visible);
        }

        // если открытая вкладка скрылась, переходим на первую видимую
        if (!MasterTabContainer.GetChild(MasterTabContainer.CurrentTab).Visible)
        {
            for (var i = 0; i < MasterTabContainer.ChildCount; i++)
            {
                if (MasterTabContainer.GetChild(i).Visible)
                {
                    MasterTabContainer.CurrentTab = i;
                    break;
                }
            }
        }
    }

    private static IEnumerable<CommandButton> CommandButtons(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is CommandButton cb)
                yield return cb;

            foreach (var nested in CommandButtons(child))
                yield return nested;
        }
    }

    private void RunSearch(string text)
    {
        var query = text.Trim().ToLowerInvariant();
        SearchResults.RemoveAllChildren();

        if (query.Length == 0)
        {
            SearchScroll.Visible = false;
            MasterTabContainer.Visible = true;
            return;
        }

        MasterTabContainer.Visible = false;
        SearchScroll.Visible = true;

        var found = 0;
        for (var i = 0; i < MasterTabContainer.ChildCount; i++)
        {
            var tabTitle = Loc.GetString(TabTitleKey((TabIndex) i));
            foreach (var cb in CommandButtons(MasterTabContainer.GetChild(i)))
            {
                if (!cb.IsAllowed || string.IsNullOrEmpty(cb.Command))
                    continue;

                var command = cb.Command.Split(' ')[0];
                var nodes = AdminNodeLookup.NodeNames(command);
                var hay = ((cb.Text ?? string.Empty) + " " + cb.Command + " " + nodes + " " + tabTitle).ToLowerInvariant();
                if (!hay.Contains(query))
                    continue;

                var target = cb;
                var button = new Button
                {
                    Text = Loc.GetString("admin-menu-search-result", ("text", cb.Text ?? command), ("command", command), ("tab", tabTitle)),
                    HorizontalExpand = true,
                    ToolTip = string.IsNullOrEmpty(nodes)
                        ? Loc.GetString("admin-menu-button-tooltip", ("command", command))
                        : Loc.GetString("admin-menu-button-tooltip-node", ("command", command), ("nodes", nodes)),
                };
                button.OnPressed += _ => target.Activate();
                SearchResults.AddChild(button);
                found++;
            }
        }

        if (found == 0)
        {
            SearchResults.AddChild(new Label
            {
                Text = Loc.GetString("admin-menu-search-empty"),
                StyleClasses = { "LabelSubText" },
            });
        }
    }

    private static string TabTitleKey(TabIndex tab)
    {
        return tab switch
        {
            TabIndex.Admin => "admin-menu-admin-tab",
            TabIndex.Adminbus => "admin-menu-adminbus-tab",
            TabIndex.Atmos => "admin-menu-atmos-tab",
            TabIndex.Round => "admin-menu-round-tab",
            TabIndex.Server => "admin-menu-server-tab",
            TabIndex.PanicBunker => "admin-menu-panic-bunker-tab",
            TabIndex.Players => "admin-menu-players-tab",
            _ => "admin-menu-objects-tab",
        };
    }
    // _Duty-end

    protected override void Dispose(bool disposing)
    {
        _admin.AdminStatusUpdated -= RefreshTabs; // _Duty
        OnDisposed?.Invoke();
        base.Dispose(disposing);
        OnDisposed = null;
    }

    private enum TabIndex
    {
        Admin = 0,
        Adminbus,
        Atmos,
        Round,
        Server,
        PanicBunker,
        Players,
        Objects,
    }
}
