using System.Linq;
using System.Numerics;
using Content.Client._Duty.Administration;
using Content.Client.Administration.Managers;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminMenuWindow : DefaultWindow
{
    public event Action? OnDisposed;

    // _Duty-start: окно знает, какие кнопки доступны: пустые вкладки прячет, по командам ищет
    private readonly IClientAdminManager _admin;
    private readonly IClientConsoleHost _console;
    // _Duty-end

    public AdminMenuWindow()
    {
        _admin = IoCManager.Resolve<IClientAdminManager>(); // _Duty
        _console = IoCManager.Resolve<IClientConsoleHost>(); // _Duty

        MinSize = new Vector2(700, 380);
        SetSize = new Vector2(900, 560); // _Duty: окно побольше, кнопки не теснятся
        Title = Loc.GetString("admin-menu-title");
        RobustXamlLoader.Load(this);
        for (var i = 0; i < MasterTabContainer.ChildCount; i++)
        {
            MasterTabContainer.SetTabTitle(i, Loc.GetString(TabTitleKey((TabIndex) i))); // _Duty: названия из одного места
        }

        MasterTabContainer.OnTabChanged += OnTabChanged;

        // _Duty-start: поиск и скрытие пустых вкладок
        SearchBar.OnTextChanged += args => RunSearch(args.Text);
        _admin.AdminStatusUpdated += OnAdminStatusUpdated;
        OnOpen += RefreshTabs;
        // _Duty-end
    }

    private void OnTabChanged(int tabIndex)
    {
        var tabEnum = (TabIndex)tabIndex;
        if (tabEnum == TabIndex.Objects)
            ObjectsTabControl.RefreshObjectList();
    }

    // _Duty-start
    private void OnAdminStatusUpdated()
    {
        RefreshTabs();

        // результаты поиска могли устареть: права изменились
        if (SearchBar.Text.Length > 0)
            RunSearch(SearchBar.Text);
    }

    /// <summary>Скрывает вкладки, где не осталось ни одной доступной кнопки.</summary>
    private void RefreshTabs()
    {
        for (var i = 0; i < MasterTabContainer.ChildCount; i++)
        {
            MasterTabContainer.SetTabVisible(i, IsTabUseful((TabIndex) i, MasterTabContainer.GetChild(i)));
        }

        // если открытая вкладка скрылась, переходим на первую видимую
        if (!MasterTabContainer.GetTabVisible(MasterTabContainer.CurrentTab))
        {
            for (var i = 0; i < MasterTabContainer.ChildCount; i++)
            {
                if (MasterTabContainer.GetTabVisible(i))
                {
                    MasterTabContainer.CurrentTab = i;
                    break;
                }
            }
        }
    }

    private bool IsTabUseful(TabIndex tab, Control control)
    {
        // Игроки и Объекты — списки, а не кнопки: нужны любому админу
        if (tab is TabIndex.Players or TabIndex.Objects)
            return true;

        // АдминАбуз содержит кнопки спавна без команд: их открывает право спавна
        if (tab == TabIndex.Adminbus && _admin.CanAdminPlace())
            return true;

        return CommandButtons(control).Any(b => b.IsAllowed)
               || control is IAdminMenuCommandSource source && source.MenuCommands.Any(c => _admin.CanCommand(c.Command));
    }

    private static IEnumerable<CommandButton> CommandButtons(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is CommandButton cb)
                yield return cb;

            foreach (var nested in CommandButtons(child))
                yield return nested;
        }
    }

    private void RunSearch(string text)
    {
        var query = text.Trim().ToLowerInvariant();
        SearchResults.RemoveAllChildren();

        if (query.Length == 0)
        {
            SearchScroll.Visible = false;
            MasterTabContainer.Visible = true;
            return;
        }

        MasterTabContainer.Visible = false;
        SearchScroll.Visible = true;

        var found = 0;
        for (var i = 0; i < MasterTabContainer.ChildCount; i++)
        {
            var tabTitle = Loc.GetString(TabTitleKey((TabIndex) i));
            var control = MasterTabContainer.GetChild(i);

            foreach (var cb in CommandButtons(control))
            {
                if (!cb.IsAllowed || string.IsNullOrEmpty(cb.Command))
                    continue;

                var target = cb;
                if (TryAddResult(query, cb.Text, cb.Command, tabTitle, false, () => target.Activate()))
                    found++;
            }

            if (control is not IAdminMenuCommandSource source)
                continue;

            foreach (var (button, command, confirm) in source.MenuCommands)
            {
                if (!_admin.CanCommand(command))
                    continue;

                var cmd = command;
                var label = button is Button b ? b.Text : null;
                if (TryAddResult(query, label, cmd, tabTitle, confirm, () => _console.ExecuteCommand(cmd)))
                    found++;
            }
        }

        if (found == 0)
        {
            SearchResults.AddChild(new Label
            {
                Text = Loc.GetString("admin-menu-search-empty"),
                StyleClasses = { "LabelSubText" },
            });
        }
    }

    /// <summary>Добавляет строку результата, если кнопка подходит под запрос. Опасные действия — с подтверждением.</summary>
    private bool TryAddResult(string query, string? text, string fullCommand, string tabTitle, bool confirm, Action act)
    {
        var command = fullCommand.Split(' ')[0];
        var nodes = AdminNodeLookup.NodeNames(command);
        var hay = ((text ?? string.Empty) + " " + fullCommand + " " + nodes + " " + tabTitle).ToLowerInvariant();
        if (!hay.Contains(query))
            return false;

        var caption = Loc.GetString("admin-menu-search-result", ("text", text ?? command), ("command", command), ("tab", tabTitle));
        var tooltip = AdminNodeLookup.Tooltip(fullCommand);

        if (confirm)
        {
            var button = new ConfirmButton { Text = caption, HorizontalExpand = true, ToolTip = tooltip };
            button.OnPressed += _ => act();
            SearchResults.AddChild(button);
        }
        else
        {
            var button = new Button { Text = caption, HorizontalExpand = true, ToolTip = tooltip };
            button.OnPressed += _ => act();
            SearchResults.AddChild(button);
        }

        return true;
    }

    private static string TabTitleKey(TabIndex tab)
    {
        return tab switch
        {
            TabIndex.Admin => "admin-menu-admin-tab",
            TabIndex.Adminbus => "duty-admin-menu-adminbus-tab",
            TabIndex.Atmos => "admin-menu-atmos-tab",
            TabIndex.Round => "admin-menu-round-tab",
            TabIndex.Server => "admin-menu-server-tab",
            TabIndex.PanicBunker => "duty-admin-menu-panic-bunker-tab",
            TabIndex.Players => "admin-menu-players-tab",
            _ => "admin-menu-objects-tab",
        };
    }
    // _Duty-end

    protected override void Dispose(bool disposing)
    {
        _admin.AdminStatusUpdated -= OnAdminStatusUpdated; // _Duty
        OnDisposed?.Invoke();
        base.Dispose(disposing);
        OnDisposed = null;
    }

    private enum TabIndex
    {
        Admin = 0,
        Adminbus,
        Atmos,
        Round,
        Server,
        PanicBunker,
        Players,
        Objects,
    }
}
