// SPDX-FileCopyrightText: 2025 LocalDuty <https://github.com/Bebranot/LocalDuty_Reserve>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.Lathe;
using Content.Client.Materials;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Lathe;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Duty.LatheUi;

/// <summary>
/// Меню любого станка (автолат, техфабы, импринтер, экзофабрикатор, биогенератор…): категории слева,
/// список рецептов с ценой в центре, очередь с прогрессом и материалы справа.
/// Подстраивается под станок: кнопка серверов — только у станков с исследованиями, мензурка — только у тех,
/// где рецептам нужны реагенты, цвет шапки — по каналу отдела, куда станок сообщает о новых рецептах.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DutyLatheMenu : FancyWindow
{
    private const string CategoryAll = "duty:all";
    private const string CategoryAvailable = "duty:available";
    private const string CategoryOther = "duty:other";

    private static readonly TimeSpan DoubleClickTime = TimeSpan.FromSeconds(0.4);

    /// <summary>
    /// Как часто перепроверять доступность. Хранилище руды и мензурка меняются без обновления состояния станка,
    /// поэтому совсем без опроса цвета устаревали бы.
    /// </summary>
    private const float AvailabilityRefreshInterval = 0.5f;

    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private readonly SpriteSystem _sprite;
    private readonly LatheSystem _lathe;
    private readonly MaterialStorageSystem _materialStorage;
    private readonly ItemSlotsSystem _itemSlots;
    private readonly SharedSolutionContainerSystem _solution;

    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed;
    public event Action<string, int>? RecipeQueueAction;
    public event Action<int>? QueueDeleteAction;
    public event Action<int>? QueueMoveUpAction;
    public event Action<int>? QueueMoveDownAction;
    public event Action? DeleteFabricatingAction;

    public EntityUid Entity;

    // Рецепты: строки живут всё время окна, фильтр только переключает Visible.
    private readonly Dictionary<ProtoId<LatheRecipePrototype>, DutyLatheRecipeRow> _rows = new();
    private readonly List<DutyLatheRecipeRow> _sortedRows = new();
    private readonly Dictionary<string, DutyLatheCategoryButton> _categoryButtons = new();
    private readonly Dictionary<string, int> _categoryCounts = new();
    private readonly Dictionary<string, Texture?> _materialIcons = new();

    private string _currentCategory = CategoryAll;
    private string[] _searchTokens = Array.Empty<string>();
    private bool _onlyAvailable;
    private int _amount = 1;
    private bool _settingAmountText;

    private DutyLatheRecipeRow? _selected;
    private ProtoId<LatheRecipePrototype>? _detailRecipe;
    private string? _lastCostMarkup;
    private DutyLatheRecipeRow? _lastClickRow;
    private TimeSpan _lastClickTime;

    // Наличие материалов на момент последней проверки — общее для строк и панели выбранного рецепта.
    private readonly Dictionary<string, int> _materialAmounts = new();
    private Solution? _beakerSolution;
    private float _availabilityAccumulator;

    private float _materialMultiplier = float.NaN;
    private float _timeMultiplier = float.NaN;
    private Color _accent = DutyLatheStyle.DefaultAccent;

    // Очередь
    private readonly List<DutyLatheQueueRow> _queueRows = new();
    private LatheRecipeBatch[] _queue = Array.Empty<LatheRecipeBatch>();
    private TimeSpan? _productionStart;
    private TimeSpan _productionLength;
    private string? _currentIconRecipe;
    private double _queuedSeconds;
    private int _lastCurrentSeconds = -1;
    private int _lastTotalSeconds = -1;

    private Vector2 _savedSize;

    public DutyLatheMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();
        _lathe = _entMan.System<LatheSystem>();
        _materialStorage = _entMan.System<MaterialStorageSystem>();
        _itemSlots = _entMan.System<ItemSlotsSystem>();
        _solution = _entMan.System<SharedSolutionContainerSystem>();

        // Размер — тот, что игрок выставил руками в прошлый раз, но не больше экрана.
        var size = new Vector2(_cfg.GetCVar(DutyCCVars.LatheUiWidth), _cfg.GetCVar(DutyCCVars.LatheUiHeight));
        var screen = UserInterfaceManager.RootControl.Size;
        if (screen.X > 100 && screen.Y > 100)
            size = Vector2.Min(size, screen - new Vector2(40, 40));
        size = Vector2.Max(size, MinSize);
        SetSize = size;
        _savedSize = size;

        ServerListButton.Visible = false;
        AccentStripe.PanelOverride = new StyleBoxFlat { BackgroundColor = _accent };

        SearchBar.OnTextChanged += _ => OnSearchChanged();
        SearchBar.OnTextEntered += _ => SelectFirstVisible();
        OnlyAvailableCheck.OnToggled += args =>
        {
            _onlyAvailable = args.Pressed;
            ApplyFilter();
        };

        AmountLineEdit.OnTextChanged += _ => OnAmountTyped();
        AmountLineEdit.OnTextEntered += _ => QueueSelected();
        AmountMinus.OnPressed += _ => SetAmount(_amount - 1);
        AmountPlus.OnPressed += _ => SetAmount(_amount + 1);
        Amount1.OnPressed += _ => SetAmount(1);
        Amount5.OnPressed += _ => SetAmount(5);
        Amount10.OnPressed += _ => SetAmount(10);
        Amount30.OnPressed += _ => SetAmount(30);
        QueueButton.OnPressed += _ => QueueSelected();

        ServerListButton.OnPressed += args => OnServerListButtonPressed?.Invoke(args);
        DeleteFabricating.OnPressed += _ => DeleteFabricatingAction?.Invoke();
        ClearQueueButton.OnPressed += _ => ClearQueue();

        SetAmountText(_amount);
        UpdateDetail();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        this.SetInfoFromEntity(_entMan, uid);
        MaterialsList.SetOwner(uid);

        if (_entMan.TryGetComponent<LatheComponent>(uid, out var lathe))
        {
            ServerListButton.Visible = lathe.DynamicPacks.Count > 0;
            SetAmount(lathe.DefaultProductionAmount);
        }
    }

    #region Состояние с сервера

    public void UpdateState(LatheUpdateState state)
    {
        _entMan.TryGetComponent<LatheComponent>(Entity, out var lathe);

        var multipliersChanged = false;
        if (lathe != null
            && (!MathHelper.CloseTo(lathe.FinalMaterialMultiplier, _materialMultiplier)
                || !MathHelper.CloseTo(lathe.FinalTimeMultiplier, _timeMultiplier)))
        {
            _materialMultiplier = lathe.FinalMaterialMultiplier;
            _timeMultiplier = lathe.FinalTimeMultiplier;
            multipliersChanged = true;
        }

        UpdateBadges(state, lathe);
        SyncRecipes(state.Recipes, lathe, multipliersChanged);
        RefreshAvailability();
        ApplyFilter();
        UpdateDetail();
        UpdateQueue(state, lathe);
    }

    /// <summary>
    /// Привести строки к списку рецептов с сервера. Список меняется редко (исследование, емаг, чертёж),
    /// поэтому здесь только добавляем недостающие и убираем лишние — существующие не трогаем.
    /// </summary>
    private void SyncRecipes(List<ProtoId<LatheRecipePrototype>> recipes, LatheComponent? lathe, bool multipliersChanged)
    {
        var changed = recipes.Count != _rows.Count;
        if (!changed)
        {
            foreach (var id in recipes)
            {
                if (_rows.ContainsKey(id))
                    continue;

                changed = true;
                break;
            }
        }

        var created = new HashSet<DutyLatheRecipeRow>();
        if (changed)
        {
            var wanted = new HashSet<ProtoId<LatheRecipePrototype>>(recipes);
            foreach (var (id, row) in _rows.ToList())
            {
                if (wanted.Contains(id))
                    continue;

                if (_selected == row)
                    _selected = null;

                if (_lastClickRow == row)
                    _lastClickRow = null;

                row.Orphan();
                _rows.Remove(id);
            }

            foreach (var id in recipes)
            {
                if (_rows.ContainsKey(id) || !_proto.Resolve(id, out var proto))
                    continue;

                var row = CreateRow(proto, lathe);
                _rows[id] = row;
                created.Add(row);
            }

            _sortedRows.Clear();
            _sortedRows.AddRange(_rows.Values.OrderBy(r => r.RecipeName, StringComparer.CurrentCultureIgnoreCase));

            // Переставляем, а не пересоздаём: выход из дерева удалил бы сущность иконки и заспавнил заново.
            for (var i = 0; i < _sortedRows.Count; i++)
            {
                var row = _sortedRows[i];
                if (row.Parent == null)
                    RecipeList.AddChild(row);
                row.SetPositionInParent(i);
            }

            RebuildCategories();
        }

        if (!multipliersChanged)
            return;

        foreach (var row in _sortedRows)
        {
            if (!created.Contains(row))
                row.SetCosts(BuildCosts(row.Recipe, lathe), EstimateSeconds(row.Recipe, lathe));
        }

        _lastCostMarkup = null;
    }

    private DutyLatheRecipeRow CreateRow(LatheRecipePrototype recipe, LatheComponent? lathe)
    {
        var row = new DutyLatheRecipeRow(recipe,
            _lathe.GetRecipeName(recipe),
            _lathe.GetRecipeDescription(recipe),
            CreateIcon(recipe, 32))
        {
            Accent = _accent,
        };
        row.SetCosts(BuildCosts(recipe, lathe), EstimateSeconds(recipe, lathe));
        row.OnPressed += _ => OnRowPressed(row);
        return row;
    }

    private List<DutyLatheCost> BuildCosts(LatheRecipePrototype recipe, LatheComponent? lathe)
    {
        var multiplier = lathe?.FinalMaterialMultiplier ?? 1f;
        var costs = new List<DutyLatheCost>();

        foreach (var (id, amount) in recipe.Materials)
        {
            if (!_proto.Resolve(id, out var material))
                continue;

            var adjusted = SharedLatheSystem.AdjustMaterial(amount, recipe.ApplyMaterialDiscount, multiplier);
            var sheetVolume = Math.Max(1, _materialStorage.GetSheetVolume(material));

            if (!_materialIcons.TryGetValue(id.Id, out var icon))
            {
                icon = material.Icon == SpriteSpecifier.Invalid ? null : _sprite.Frame0(material.Icon);
                _materialIcons[id.Id] = icon;
            }

            costs.Add(new DutyLatheCost
            {
                Id = id.Id,
                Needed = adjusted,
                Shown = adjusted / (float) sheetVolume,
                PerShown = sheetVolume,
                Name = Loc.GetString(material.Name),
                Icon = icon,
                Color = material.Color,
            });
        }

        // ADT: часть рецептов протолата требует реагент из мензурки в слоте станка.
        foreach (var (reagent, needed) in recipe.ReagentCost)
        {
            if (!_proto.Resolve(reagent, out var reagentProto))
                continue;

            var adjusted = SharedLatheSystem.AdjustReagentCost(needed, recipe.ApplyMaterialDiscount, multiplier).Float();
            costs.Add(new DutyLatheCost
            {
                Id = reagent.Id,
                IsReagent = true,
                Needed = adjusted,
                Shown = adjusted,
                PerShown = 1,
                Name = reagentProto.LocalizedName,
                Color = reagentProto.SubstanceColor,
            });
        }

        return costs;
    }

    /// <summary>
    /// Время одной детали так же, как его считает сервер, но без смазки (ReagentSpeed известен только серверу) —
    /// поэтому в интерфейсе оно со знаком «≈».
    /// </summary>
    private static double EstimateSeconds(LatheRecipePrototype recipe, LatheComponent? lathe)
    {
        var seconds = recipe.CompleteTime.TotalSeconds;
        if (lathe != null)
            seconds *= Math.Pow(Math.Max(0.1f, lathe.FinalTimeMultiplier), lathe.MachinePartEfficiencyExponent);

        return Math.Max(0.1, seconds);
    }

    private Control CreateIcon(LatheRecipePrototype? recipe, float size)
    {
        var setSize = new Vector2(size, size);

        if (recipe?.Icon != null)
        {
            return new TextureRect
            {
                Texture = _sprite.Frame0(recipe.Icon),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                SetSize = setSize,
            };
        }

        if (recipe?.Result is { } result)
        {
            var view = new EntityPrototypeView
            {
                SetSize = setSize,
                Stretch = SpriteView.StretchMode.Fill,
            };
            view.SetPrototype(result);
            return view;
        }

        // Рецепты-жидкости (биогенератор): иконки нет — показываем цвет первого реагента.
        if (recipe?.ResultReagents is { Count: > 0 } reagents
            && _proto.TryIndex(reagents.Keys.First(), out var reagent))
        {
            return new PanelContainer
            {
                SetSize = setSize * 0.6f,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                PanelOverride = new StyleBoxFlat { BackgroundColor = reagent.SubstanceColor },
            };
        }

        return new Control { SetSize = setSize };
    }

    #endregion

    #region Шапка

    private void UpdateBadges(LatheUpdateState state, LatheComponent? lathe)
    {
        BadgeContainer.RemoveAllChildren();

        var accent = DutyLatheStyle.DefaultAccent;
        var accentSet = false;
        foreach (var channelId in state.AnnounceChannels)
        {
            if (!_proto.TryIndex(channelId, out var channel))
                continue;

            if (!accentSet)
            {
                accent = channel.Color;
                accentSet = true;
            }

            AddBadge(Loc.GetString("duty-lathe-badge-announce", ("channel", channel.LocalizedName)),
                Loc.GetString("duty-lathe-badge-announce-tooltip", ("channel", channel.LocalizedName)),
                channel.Color);
        }

        SetAccent(accent);

        if (lathe == null)
            return;

        if (lathe.DynamicPacks.Count > 0)
        {
            AddBadge(Loc.GetString("duty-lathe-badge-research"),
                Loc.GetString("duty-lathe-badge-research-tooltip"),
                Color.FromHex("#9FB6FF"));
        }

        if (_entMan.HasComponent<BlueprintReceiverComponent>(Entity))
        {
            AddBadge(Loc.GetString("duty-lathe-badge-blueprint"),
                Loc.GetString("duty-lathe-badge-blueprint-tooltip"),
                Color.FromHex("#8FD3FF"));
        }

        if (state.HasReagentSlot)
        {
            AddBadge(Loc.GetString(state.BeakerInserted ? "duty-lathe-badge-beaker-in" : "duty-lathe-badge-beaker-out"),
                Loc.GetString("duty-lathe-badge-beaker-tooltip"),
                state.BeakerInserted ? DutyLatheStyle.Good : DutyLatheStyle.Bad);
        }

        if (lathe.ReagentOutputSlotId != null)
        {
            AddBadge(Loc.GetString("duty-lathe-badge-reagent-output"),
                Loc.GetString("duty-lathe-badge-reagent-output-tooltip"),
                Color.FromHex("#B0E0A0"));
        }

        if (!lathe.SuppressMachinePartUpgrades && lathe.FinalTimeMultiplier > 0f)
        {
            var speed = (int) MathF.Round(lathe.TimeMultiplier / lathe.FinalTimeMultiplier * 100f);
            var cost = (int) MathF.Round(lathe.FinalMaterialMultiplier / MathF.Max(0.01f, lathe.MaterialUseMultiplier) * 100f);
            if (speed != 100 || cost != 100)
            {
                AddBadge(Loc.GetString("duty-lathe-badge-parts", ("speed", speed), ("cost", cost)),
                    Loc.GetString("duty-lathe-badge-parts-tooltip"),
                    DutyLatheStyle.TextMuted);
            }
        }
    }

    private void AddBadge(string text, string tooltip, Color color)
    {
        var badge = new DutyLatheBadge();
        badge.Set(text, tooltip, color);
        BadgeContainer.AddChild(badge);
    }

    private void SetAccent(Color accent)
    {
        if (_accent == accent)
            return;

        _accent = accent;
        AccentStripe.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };

        foreach (var row in _sortedRows)
        {
            row.Accent = accent;
        }

        foreach (var button in _categoryButtons.Values)
        {
            button.Accent = accent;
        }
    }

    #endregion

    #region Категории, поиск, фильтр

    private void RebuildCategories()
    {
        CategoryList.RemoveAllChildren();
        _categoryButtons.Clear();

        AddCategoryButton(CategoryAll, Loc.GetString("duty-lathe-category-all"));
        AddCategoryButton(CategoryAvailable, Loc.GetString("duty-lathe-category-available"));
        CategoryList.AddChild(new Control { MinHeight = 6 });

        var categories = new HashSet<ProtoId<LatheCategoryPrototype>>();
        var hasOther = false;
        foreach (var row in _sortedRows)
        {
            if (row.Recipe.Categories.Count == 0)
                hasOther = true;
            else
                categories.UnionWith(row.Recipe.Categories);
        }

        var sorted = new List<(string Id, string Name)>();
        foreach (var id in categories)
        {
            if (_proto.Resolve(id, out var category))
                sorted.Add((category.ID, Loc.GetString(category.Name)));
        }

        sorted.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
        foreach (var (id, name) in sorted)
        {
            AddCategoryButton(id, name);
        }

        if (hasOther)
            AddCategoryButton(CategoryOther, Loc.GetString("duty-lathe-category-other"));

        if (!_categoryButtons.ContainsKey(_currentCategory))
            _currentCategory = CategoryAll;

        UpdateCategorySelection();
    }

    private void AddCategoryButton(string key, string name)
    {
        var button = new DutyLatheCategoryButton(key, name) { Accent = _accent };
        button.OnPressed += _ =>
        {
            _currentCategory = key;
            UpdateCategorySelection();
            ApplyFilter();
        };
        CategoryList.AddChild(button);
        _categoryButtons[key] = button;
    }

    private void UpdateCategorySelection()
    {
        foreach (var (key, button) in _categoryButtons)
        {
            button.Selected = key == _currentCategory;
        }
    }

    private void OnSearchChanged()
    {
        _searchTokens = DutyLatheSearch.Normalize(SearchBar.Text)
            .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        ApplyFilter();
    }

    /// <summary>
    /// Один проход по строкам: видимость + счётчики категорий. Ничего не создаётся и не удаляется,
    /// поэтому поиск не лагает даже на техфабе с сотнями рецептов.
    /// </summary>
    private void ApplyFilter()
    {
        _categoryCounts.Clear();
        var total = 0;
        var available = 0;
        var other = 0;
        var visible = 0;

        foreach (var row in _sortedRows)
        {
            var match = MatchesSearch(row) && (!_onlyAvailable || row.CanProduce);
            if (match)
            {
                total++;
                if (row.CanProduce)
                    available++;

                if (row.Recipe.Categories.Count == 0)
                    other++;

                foreach (var category in row.Recipe.Categories)
                {
                    _categoryCounts[category.Id] = _categoryCounts.GetValueOrDefault(category.Id) + 1;
                }
            }

            var show = match && _currentCategory switch
            {
                CategoryAll => true,
                CategoryAvailable => row.CanProduce,
                CategoryOther => row.Recipe.Categories.Count == 0,
                _ => HasCategory(row, _currentCategory),
            };

            row.Visible = show;
            if (show)
                visible++;
        }

        foreach (var (key, button) in _categoryButtons)
        {
            button.SetCount(key switch
            {
                CategoryAll => total,
                CategoryAvailable => available,
                CategoryOther => other,
                _ => _categoryCounts.GetValueOrDefault(key),
            });
        }

        NoResultsLabel.Visible = visible == 0;
    }

    private bool MatchesSearch(DutyLatheRecipeRow row)
    {
        // Все слова запроса в любом порядке: «5.45 бронеб» найдёт «Коробка 5.45×39 бронебойные».
        foreach (var token in _searchTokens)
        {
            if (!row.SearchText.Contains(token, StringComparison.Ordinal))
                return false;
        }

        return true;
    }

    private static bool HasCategory(DutyLatheRecipeRow row, string category)
    {
        foreach (var id in row.Recipe.Categories)
        {
            if (id.Id == category)
                return true;
        }

        return false;
    }

    private void SelectFirstVisible()
    {
        foreach (var row in _sortedRows)
        {
            if (!row.Visible)
                continue;

            Select(row);
            return;
        }
    }

    #endregion

    #region Доступность и выбранный рецепт

    /// <summary>
    /// Перекрасить строки по наличию материалов. Количество каждого материала спрашиваем один раз,
    /// а не на каждый рецепт, как это делал CanProduce. Возвращает true, если у какой-то строки сменилась доступность.
    /// </summary>
    private bool RefreshAvailability()
    {
        _materialAmounts.Clear();
        foreach (var row in _sortedRows)
        {
            foreach (var cost in row.Costs)
            {
                if (!cost.IsReagent && !_materialAmounts.ContainsKey(cost.Id))
                    _materialAmounts[cost.Id] = _materialStorage.GetMaterialAmount(Entity, cost.Id);
            }
        }

        _beakerSolution = GetBeakerSolution();

        var changed = false;
        foreach (var row in _sortedRows)
        {
            changed |= row.RefreshAvailability(_materialAmounts, _beakerSolution, _amount);
        }

        return changed;
    }

    private Solution? GetBeakerSolution()
    {
        if (!_entMan.TryGetComponent<LatheComponent>(Entity, out var lathe)
            || lathe.ReagentCostSlotId is not { } slotId
            || _itemSlots.GetItemOrNull(Entity, slotId) is not { } beaker
            || !_solution.TryGetFitsInDispenser(beaker, out _, out var solution))
        {
            return null;
        }

        return solution;
    }

    private void OnRowPressed(DutyLatheRecipeRow row)
    {
        var now = _timing.RealTime;
        if (_lastClickRow == row && now - _lastClickTime <= DoubleClickTime)
        {
            _lastClickRow = null;
            Select(row);
            QueueSelected();
            return;
        }

        _lastClickRow = row;
        _lastClickTime = now;
        Select(row);
    }

    private void Select(DutyLatheRecipeRow row)
    {
        if (_selected != null)
            _selected.Selected = false;

        _selected = row;
        row.Selected = true;
        UpdateDetail();
    }

    private void QueueSelected()
    {
        if (_selected == null || !_selected.CanProduce)
            return;

        RecipeQueueAction?.Invoke(_selected.Recipe.ID, _amount);
    }

    private void UpdateDetail()
    {
        var row = _selected;
        DetailHint.Visible = row == null;
        DetailBody.Visible = row != null;
        QueueButton.Disabled = row == null || !row.CanProduce;
        QueueButton.Text = _amount > 1
            ? Loc.GetString("duty-lathe-to-queue-many", ("amount", _amount))
            : Loc.GetString("duty-lathe-to-queue");

        if (row == null)
        {
            DetailTime.Text = string.Empty;
            _detailRecipe = null;
            return;
        }

        if (_detailRecipe != row.Recipe.ID)
        {
            _detailRecipe = row.Recipe.ID;
            _lastCostMarkup = null;
            DetailIcon.RemoveAllChildren();
            DetailIcon.AddChild(CreateIcon(row.Recipe, 64));
            DetailName.Text = row.RecipeName;
            DetailName.ToolTip = row.RecipeName;

            var description = _lathe.GetRecipeDescription(row.Recipe);
            DetailDescription.SetMarkupPermissive(string.IsNullOrWhiteSpace(description)
                ? string.Empty
                : $"[italic]{FormattedMessage.EscapeText(description)}[/italic]");
        }

        var markup = BuildCostMarkup(row);
        if (markup != _lastCostMarkup)
        {
            _lastCostMarkup = markup;
            DetailCost.SetMarkupPermissive(markup);
        }

        DetailTime.Text = Loc.GetString("duty-lathe-time-total", ("time", DutyLatheStyle.FormatTime(row.ItemSeconds * _amount)));
    }

    private string BuildCostMarkup(DutyLatheRecipeRow row)
    {
        var sb = new StringBuilder();
        sb.Append(Loc.GetString("duty-lathe-cost-title", ("amount", _amount)));

        if (row.Costs.Count == 0)
            sb.Append(' ').Append(Loc.GetString("duty-lathe-cost-free"));

        var first = true;
        foreach (var cost in row.Costs)
        {
            sb.Append(first ? " " : "  ·  ");
            first = false;

            var name = FormattedMessage.EscapeText(cost.Name);
            if (cost.IsReagent && _beakerSolution == null)
            {
                sb.Append(Loc.GetString("duty-lathe-cost-reagent-no-beaker",
                    ("name", name),
                    ("need", DutyLatheStyle.FormatAmount(cost.Shown * _amount))));
                continue;
            }

            var have = DutyLatheRecipeRow.Have(cost, _materialAmounts, _beakerSolution) / cost.PerShown;
            var enough = DutyLatheRecipeRow.HasEnough(cost, _materialAmounts, _beakerSolution, _amount);
            sb.Append(Loc.GetString(cost.IsReagent ? "duty-lathe-cost-reagent" : "duty-lathe-cost-material",
                ("name", name),
                ("need", DutyLatheStyle.FormatAmount(cost.Shown * _amount)),
                ("have", DutyLatheStyle.FormatAmount(have)),
                ("color", (enough ? DutyLatheStyle.Good : DutyLatheStyle.Bad).ToHex())));
        }

        if (!row.CanProduce)
            sb.Append('\n').Append(Loc.GetString("duty-lathe-cost-not-enough"));

        return sb.ToString();
    }

    #endregion

    #region Количество

    private void SetAmount(int amount)
    {
        amount = Math.Clamp(amount, 1, SharedLatheSystem.MaxItemsPerRequest);
        SetAmountText(amount);

        if (_amount == amount)
            return;

        _amount = amount;
        if (RefreshAvailability() || _currentCategory == CategoryAvailable || _onlyAvailable)
            ApplyFilter();
        UpdateDetail();
    }

    private void SetAmountText(int amount)
    {
        _settingAmountText = true;
        AmountLineEdit.Text = amount.ToString();
        _settingAmountText = false;
    }

    private void OnAmountTyped()
    {
        if (_settingAmountText)
            return;

        // Пока игрок печатает (пустое поле, «0»), текст не трогаем — только количество.
        if (!int.TryParse(AmountLineEdit.Text, out var amount))
            return;

        if (amount > SharedLatheSystem.MaxItemsPerRequest)
        {
            SetAmount(amount);
            return;
        }

        amount = Math.Max(1, amount);
        if (_amount == amount)
            return;

        _amount = amount;
        if (RefreshAvailability() || _currentCategory == CategoryAvailable || _onlyAvailable)
            ApplyFilter();
        UpdateDetail();
    }

    #endregion

    #region Очередь

    private void UpdateQueue(LatheUpdateState state, LatheComponent? lathe)
    {
        _queue = state.Queue;
        _productionStart = state.ProductionStart;
        _productionLength = state.ProductionLength;

        LatheRecipePrototype? current = null;
        var producing = state.ProductionStart != null
                        && state.CurrentlyProducing is { } currentId
                        && _proto.Resolve(currentId, out current);

        CurrentPanel.Visible = producing;
        if (producing && current != null)
        {
            if (_currentIconRecipe != current.ID)
            {
                _currentIconRecipe = current.ID;
                CurrentIcon.RemoveAllChildren();
                CurrentIcon.AddChild(CreateIcon(current, 32));
            }

            var name = _lathe.GetRecipeName(current);
            CurrentName.Text = name;
            CurrentName.ToolTip = name;
        }

        // Очередь есть, а печать не идёт — сервер не запускает станок только без питания.
        PowerWarningLabel.Visible = !producing && _queue.Length > 0;
        QueueEmptyLabel.Visible = !producing && _queue.Length == 0;
        ClearQueueButton.Disabled = _queue.Length == 0;

        _queuedSeconds = 0;
        for (var i = 0; i < _queue.Length; i++)
        {
            var batch = _queue[i];
            _proto.Resolve(batch.Recipe, out var recipe);

            // ItemsPrinted уже включает деталь, которая сейчас в работе.
            var remaining = Math.Max(0, batch.ItemsRequested - batch.ItemsPrinted);
            var seconds = recipe != null ? remaining * EstimateSeconds(recipe, lathe) : 0;
            _queuedSeconds += seconds;

            var progress = seconds > 0
                ? Loc.GetString("duty-lathe-batch-progress-time",
                    ("printed", batch.ItemsPrinted),
                    ("total", batch.ItemsRequested),
                    ("time", DutyLatheStyle.FormatTime(seconds)))
                : Loc.GetString("duty-lathe-batch-progress",
                    ("printed", batch.ItemsPrinted),
                    ("total", batch.ItemsRequested));

            if (i >= _queueRows.Count)
                _queueRows.Add(CreateQueueRow());

            var name = recipe != null ? _lathe.GetRecipeName(recipe) : batch.Recipe.Id;
            _queueRows[i].Set(i, _queue.Length, batch.Recipe.Id, name, progress, () => CreateIcon(recipe, 32));
        }

        for (var i = _queueRows.Count - 1; i >= _queue.Length; i--)
        {
            _queueRows[i].Orphan();
            _queueRows.RemoveAt(i);
        }

        _lastCurrentSeconds = -1;
        _lastTotalSeconds = -1;
        UpdateTimers();
    }

    private DutyLatheQueueRow CreateQueueRow()
    {
        var row = new DutyLatheQueueRow();
        row.OnMoveUp += index => QueueMoveUpAction?.Invoke(index);
        row.OnMoveDown += index => QueueMoveDownAction?.Invoke(index);
        row.OnDelete += index => QueueDeleteAction?.Invoke(index);
        QueueList.AddChild(row);
        return row;
    }

    private void ClearQueue()
    {
        // Удаляем всегда нулевую партию: если пока идут сообщения какая-то партия допечатается,
        // индексы сдвинутся, а «первая» останется первой. Материалы сервер возвращает сам.
        for (var i = 0; i < _queue.Length; i++)
        {
            QueueDeleteAction?.Invoke(0);
        }
    }

    /// <summary>
    /// Прогресс текущей детали и общее время. Сервер присылает только момент старта и длительность,
    /// дальше тикаем на клиенте; тексты меняем, только когда сменилась секунда.
    /// </summary>
    private void UpdateTimers()
    {
        var currentRemaining = 0.0;
        if (CurrentPanel.Visible && _productionStart is { } start)
        {
            var elapsed = (_timing.CurTime - start).TotalSeconds;
            var length = _productionLength.TotalSeconds;
            CurrentProgress.Value = length > 0 ? (float) Math.Clamp(elapsed / length, 0, 1) : 1f;
            currentRemaining = Math.Max(0, length - elapsed);

            var seconds = (int) Math.Ceiling(currentRemaining);
            if (seconds != _lastCurrentSeconds)
            {
                _lastCurrentSeconds = seconds;
                CurrentStatus.Text = Loc.GetString("duty-lathe-producing", ("time", DutyLatheStyle.FormatTime(seconds)));
            }
        }

        var total = (int) Math.Ceiling(currentRemaining + _queuedSeconds);
        if (total == _lastTotalSeconds)
            return;

        _lastTotalSeconds = total;
        QueueTotalLabel.Text = total > 0
            ? Loc.GetString("duty-lathe-queue-total", ("time", DutyLatheStyle.FormatTime(total)))
            : string.Empty;
    }

    #endregion

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateTimers();

        _availabilityAccumulator += args.DeltaSeconds;
        if (_availabilityAccumulator < AvailabilityRefreshInterval)
            return;

        _availabilityAccumulator = 0;
        if (RefreshAvailability())
            ApplyFilter();

        if (_selected != null)
            UpdateDetail();
    }

    /// <summary>
    /// Размер запоминаем при закрытии: и крестиком, и когда игрок отошёл от станка (BUI закрывает окно сам).
    /// </summary>
    protected override void ExitedTree()
    {
        base.ExitedTree();

        var size = Size;
        if (size.X <= 0 || size.Y <= 0 || (size - _savedSize).LengthSquared() < 1f)
            return;

        _savedSize = size;
        _cfg.SetCVar(DutyCCVars.LatheUiWidth, size.X);
        _cfg.SetCVar(DutyCCVars.LatheUiHeight, size.Y);
        _cfg.SaveToFile();
    }
}
