using Content.Shared._Duty.ErpStatus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Duty.ErpStatus;

/// <summary>
/// _Duty: окно смены ЕРП-статуса, открывается из Escape-меню. Опрашивает текущий статус и
/// кулдаун персонажа игрока каждый кадр (пока окно открыто) и шлёт запрос на смену на сервер —
/// сам ничего не решает, финальное слово всегда за <see cref="Content.Server._Duty.ErpStatus.ErpStatusSystem"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ErpStatusWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly Robust.Client.Player.IPlayerManager _player = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly ErpStatusSystem _erpStatus;

    private DutyErpStatus _selected = DutyErpStatus.None;

    public ErpStatusWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _erpStatus = _entMan.System<ErpStatusSystem>();

        NoneButton.OnPressed += _ => SelectOption(DutyErpStatus.None);
        ModerateButton.OnPressed += _ => SelectOption(DutyErpStatus.Moderate);
        FullButton.OnPressed += _ => SelectOption(DutyErpStatus.Full);

        ApplyButton.OnPressed += _ => _erpStatus.RequestChange(_selected);
    }

    private void SelectOption(DutyErpStatus status)
    {
        _selected = status;
        UpdateOptionButtons();
        UpdateApplyButton();
    }

    protected override void FrameUpdate(Robust.Shared.Timing.FrameEventArgs args)
    {
        base.FrameUpdate(args);
        Refresh();
    }

    public void Refresh()
    {
        if (_player.LocalEntity is not { } local ||
            !_entMan.TryGetComponent<ErpStatusComponent>(local, out var comp))
        {
            CurrentStatusLabel.Text = Loc.GetString("duty-erp-status-window-no-character");
            CooldownLabel.Text = string.Empty;
            ApplyButton.Disabled = true;
            return;
        }

        CurrentStatusLabel.Text = Loc.GetString("duty-erp-status-window-current", ("status", StatusName(comp.Status)));

        var remaining = comp.NextChangeAllowedAt - _timing.CurTime;
        CooldownLabel.Text = remaining > TimeSpan.Zero
            ? Loc.GetString("duty-erp-status-window-cooldown", ("seconds", (int) Math.Ceiling(remaining.TotalSeconds)))
            : Loc.GetString("duty-erp-status-window-cooldown-ready");

        // Инициализируем выбор текущим статусом только один раз, чтобы не сбрасывать
        // невыбранный игроком вариант каждый кадр.
        if (!NoneButton.Pressed && !ModerateButton.Pressed && !FullButton.Pressed)
        {
            _selected = comp.Status;
            UpdateOptionButtons();
        }

        UpdateApplyButton();
    }

    private void UpdateOptionButtons()
    {
        NoneButton.Pressed = _selected == DutyErpStatus.None;
        ModerateButton.Pressed = _selected == DutyErpStatus.Moderate;
        FullButton.Pressed = _selected == DutyErpStatus.Full;
    }

    private void UpdateApplyButton()
    {
        if (_player.LocalEntity is not { } local ||
            !_entMan.TryGetComponent<ErpStatusComponent>(local, out var comp))
        {
            ApplyButton.Disabled = true;
            return;
        }

        var onCooldown = _timing.CurTime < comp.NextChangeAllowedAt;
        ApplyButton.Disabled = onCooldown || _selected == comp.Status;
    }

    private static string StatusName(DutyErpStatus status)
    {
        return status switch
        {
            DutyErpStatus.None => Loc.GetString("duty-erp-status-option-none"),
            DutyErpStatus.Moderate => Loc.GetString("duty-erp-status-option-moderate"),
            DutyErpStatus.Full => Loc.GetString("duty-erp-status-option-full"),
            _ => Loc.GetString("duty-erp-status-option-none"),
        };
    }
}
