// SPDX-FileCopyrightText: 2026 LocalDuty <https://github.com/Bebranot/LocalDuty_Reserve>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Duty.CodeAlpha;

/// <summary>
/// _Duty: окно подтверждения кода «Альфа» у хоста сервера.
///
/// Своё окно, а не <c>QuickDialogSystem</c>: тот умеет только текстовые и числовые поля, а
/// <c>OpenDialogInternal</c> приватный — чистой кнопки «да/нет» там не получить, не патча upstream.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DutyCodeAlphaConfirmWindow : FancyWindow
{
    /// <summary>Поле, а не event: систему нужно уметь отписать снаружи при закрытии окна.</summary>
    public Action<bool>? OnAnswered;

    private TimeSpan _expiresAt;

    public DutyCodeAlphaConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Answer(true);
        DenyButton.OnPressed += _ => Answer(false);
    }

    public void SetPrompt(string body, TimeSpan expiresAt)
    {
        BodyLabel.SetMessage(body);
        _expiresAt = expiresAt;
    }

    /// <summary>
    /// Обновляет надпись «автоматически через N с». Вызывается контроллером, потому что у окна
    /// нет доступа к игровому времени сервера.
    /// </summary>
    public void UpdateCountdown(TimeSpan now)
    {
        var left = _expiresAt - now;
        if (left < TimeSpan.Zero)
            left = TimeSpan.Zero;

        CountdownLabel.Text = Loc.GetString(
            "duty-code-alpha-prompt-timer",
            ("seconds", (int)Math.Ceiling(left.TotalSeconds)));
    }

    private void Answer(bool confirmed)
    {
        // Отписываемся сразу: закрытие окна не должно повторно отправить ответ.
        var handler = OnAnswered;
        OnAnswered = null;
        handler?.Invoke(confirmed);

        Close();
    }
}
