// SPDX-FileCopyrightText: 2026 LocalDuty <https://github.com/Bebranot/LocalDuty_Reserve>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Resources;
using Content.Shared._Duty.CodeAlpha;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;

namespace Content.Client._Duty.CodeAlpha;

/// <summary>
/// _Duty: панель обратного отсчёта кода «Альфа» в правом нижнем углу.
///
/// Прячется двойным ПКМ. Кейбинда для возврата нет — вместо него контроллер сам показывает
/// панель на ключевых остатках (см. <see cref="DutyCodeAlphaVisuals.ReshowThresholds"/>),
/// иначе случайно закрывший её игрок остался бы без таймера до конца раунда.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DutyCodeAlphaTimerWidget : UIWidget
{
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    /// <summary>Игрок спрятал панель вручную. Сбрасывается контроллером на порогах.</summary>
    public bool Dismissed;

    /// <summary>
    /// Время предыдущего ПКМ. Именно nullable, а не TimeSpan.MinValue: разность
    /// <c>RealTime - TimeSpan.MinValue</c> не влезает в long, и TimeSpan бросил бы
    /// OverflowException на первом же клике.
    /// </summary>
    private TimeSpan? _lastRightClick;

    public DutyCodeAlphaTimerWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Панель должна ловить ПКМ, иначе клик уйдёт сквозь неё в игровой мир.
        MouseFilter = MouseFilterMode.Stop;

        var color = Color.FromHex(DutyCodeAlphaVisuals.Color);

        Panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0f, 0f, 0f, 0.55f),
            BorderColor = color,
            BorderThickness = new Thickness(1),
        };

        TitleLabel.FontOverride = _resCache.GetFont(DutyCodeAlphaVisuals.FontPath, DutyCodeAlphaVisuals.FontSize - 8);
        TitleLabel.FontColorOverride = color;
        TitleLabel.Text = Loc.GetString("duty-code-alpha-timer-title");

        TimerLabel.FontOverride = _resCache.GetFont(DutyCodeAlphaVisuals.FontPath, DutyCodeAlphaVisuals.FontSize);
        TimerLabel.FontColorOverride = color;
    }

    public void SetRemaining(TimeSpan remaining)
    {
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        TimerLabel.Text = remaining.ToString(@"mm\:ss");
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIRightClick)
            return;

        args.Handle();

        var now = _timing.RealTime;
        if (_lastRightClick is { } last && now - last <= DutyCodeAlphaVisuals.DoubleClickWindow)
        {
            Dismissed = true;
            Visible = false;
            _lastRightClick = null;
            return;
        }

        _lastRightClick = now;
    }
}
