using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Lobby;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Roles;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;
using Content.Client.Corvax.Sponsors;

namespace Content.Client.ADT.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    public event Action<ProtoId<SpeciesPrototype>>? ChooseAction;
    public ProtoId<SpeciesPrototype> CurrentSpecies;

    public HumanoidCharacterProfile Profile;
    private readonly IEntityManager _entityManager;
    private readonly IPrototypeManager _proto;
    private readonly LobbyUIController _uIController;
    private readonly IResourceManager _resMan;
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly Content.Client.ADT.Sponsors.SponsorManager _adtSponsors = default!;
    [Dependency] private readonly Robust.Client.Player.IPlayerManager _players = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public SpeciesWindow(HumanoidCharacterProfile profile,
                        IPrototypeManager proto,
                        IEntityManager entMan,
                        LobbyUIController uIController,
                        IResourceManager resManager,
                        DocumentParsingManager parsing)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = Loc.GetString("species-window-title");

        Profile = profile;
        _entityManager = entMan;
        _proto = proto;
        _uIController = uIController;
        _resMan = resManager;

        CurrentSpecies = Profile.Species;

        // _Duty: раньше подписка на Select добавлялась при каждом SelectSpecies и срабатывала N раз.
        Select.OnPressed += _ => ChooseAction?.Invoke(CurrentSpecies);

        BuildSpeciesList();
        SelectSpecies(Profile.Species);

        _adtSponsors.Updated += OnSponsorsUpdated;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            _adtSponsors.Updated -= OnSponsorsUpdated;
            DeletePreviewEntities(); // _Duty: превью-сущности раньше не удалялись
        }
    }

    // _Duty: сущности превью живут, пока окно открыто; при выборе другого вида старые удаляются.
    private EntityUid? _mobEntity;
    private EntityUid? _loadoutMobEntity;

    private void DeletePreviewEntities()
    {
        if (_mobEntity is { } mob && _entityManager.EntityExists(mob))
            _entityManager.DeleteEntity(mob);
        if (_loadoutMobEntity is { } loadoutMob && _entityManager.EntityExists(loadoutMob))
            _entityManager.DeleteEntity(loadoutMob);

        _mobEntity = null;
        _loadoutMobEntity = null;
    }

    private void OnSponsorsUpdated()
    {
        if (Disposed)
            return;

        BuildSpeciesList();
    }

    private void BuildSpeciesList()
    {
        SpeciesContainer.RemoveAllChildren();

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart).ToList();
        protoList.Sort((x, y) => string.Compare(LocOrLiteral(x.Name), LocOrLiteral(y.Name), StringComparison.CurrentCultureIgnoreCase)); // _Duty: по всему названию

        AddLabel(Loc.GetString("duty-species-category-classic"));
        AddCategoryButtons(protoList, SpeciesCategory.Classic);

        AddLabel(Loc.GetString("duty-species-category-unusual"));
        AddCategoryButtons(protoList, SpeciesCategory.Unusual);

        AddLabel(Loc.GetString("duty-species-category-special"));
        AddCategoryButtons(protoList, SpeciesCategory.Special);

        var localSession = _players.LocalSession;

        if (IoCManager.Resolve<SponsorsManager>().TryGetInfo(out var sponsor) || _adtSponsors.Data.HasAnyBenefit)
        {
            AddLabel(Loc.GetString("duty-species-category-sponsor"));
            foreach (var item in protoList.Where(x => x.Category == SpeciesCategory.Sponsor))
            {
                if (item.SponsorOnly && !_adtSponsors.IsSpeciesAllowed(localSession, item.ID) && sponsor == null)
                    continue;

                AddSpeciesButton(item);
            }
        }
    }

    private void AddCategoryButtons(List<SpeciesPrototype> protoList, SpeciesCategory category)
    {
        foreach (var item in protoList.Where(x => x.Category == category))
        {
            AddSpeciesButton(item);
        }
    }

    private void AddSpeciesButton(SpeciesPrototype item)
    {
        var button = new SpeciesButton(item)
        {
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = CurrentSpecies == item.ID,
            Text = LocOrLiteral(item.Name),
            Margin = new Thickness(5f, 5f),
        };
        button.OnToggled += _ => SelectSpecies(item.ID);
        SpeciesContainer.AddChild(button);
    }

    private string LocOrLiteral(string id)
        => _loc.TryGetString(id, out var value) ? value : id;

    private void AddLabel(string text)
    {
        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
        };
        var label = new Label()
        {
            Text = text,
            StyleClasses = { "LowDivider" },
            Margin = new(2f, 2f),
        };
        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };
        container.AddChild(label);
        container.AddChild(separator);

        SpeciesContainer.AddChild(container);
    }

    public void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;
            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index(protoId);
        // _Duty: без профессии с высоким приоритетом First() падал.
        var highJob = Profile.JobPriorities.FirstOrDefault(x => x.Value == JobPriority.High).Key;
        var job = string.IsNullOrEmpty(highJob) ? SharedGameTicker.FallbackOverflowJob : highJob;
        CurrentSpecies = protoId;

        var previewProfile = Profile;
        previewProfile = previewProfile.WithSpecies(protoId);

        previewProfile = previewProfile.WithCharacterAppearance(
            HumanoidCharacterAppearance.EnsureValid(previewProfile.Appearance, protoId, previewProfile.Sex));

        DeletePreviewEntities();

        var mob = _uIController.LoadProfileEntity(previewProfile, _proto.Index<JobPrototype>(job), false);  // Раздетый моб
        _mobEntity = mob;
        Mob.SetEntity(mob);

        var loadoutMob = _uIController.LoadProfileEntity(previewProfile, _proto.Index<JobPrototype>(job), true);    // Моб в одежде должности
        _loadoutMobEntity = loadoutMob;
        JobLoadout.SetEntity(loadoutMob);

        Select.Disabled = Profile.Species == protoId;

        // Тут у нас идёт штука для создание контейнера плюсов и минусов. Я не уверен, зачем я впихнул это сюда, но мне уже лень переделывать
        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };
        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { "LowDivider" },
            Margin = new(2f, 2f),
        };
        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };
        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        if (proto.Pros.Count <= 0 && proto.Special.Count <= 0 && proto.Cons.Count <= 0)
        {
            var noProsConsLabel = new RichTextLabel()
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new(4f),
            };
            DetailInfoContainer.AddChild(noProsConsLabel);
        }
        else
        {
            if (proto.Pros.Count > 0)
            {
                foreach (var item in proto.Pros)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#13f244]- " + LocOrLiteral(item) + "[/color]",
                        StyleClasses = { "LowDivider" },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Special.Count > 0)
            {
                foreach (var item in proto.Special)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "- " + LocOrLiteral(item),
                        StyleClasses = { "LowDivider" },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Cons.Count > 0)
            {
                foreach (var item in proto.Cons)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#d63636]- " + LocOrLiteral(item) + "[/color]",
                        StyleClasses = { "LowDivider" },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }
        }

        if (!proto.Description.HasValue)
            return;

        // Описания рас берут текст из .xml файлов, поэтому нам нужно найти и использовать контент из указанного файла.
        // По сути, всё работает так же, как и в гайдбуке (и да, сюда можно вставлять изображения)
        using var file = _resMan.ContentFileReadText(proto.Description.Value);
        _parsingMan.TryAddMarkup(DetailInfoContainer, file.ReadToEnd());
    }

    private sealed partial class SpeciesButton(ProtoId<SpeciesPrototype> proto) : Button
    {
        public ProtoId<SpeciesPrototype> Proto = proto;
    }
}
