// SPDX-FileCopyrightText: 2026 LocalDuty
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared._Duty.SpawnMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Duty.SpawnMenu;

/// <summary>
/// Список доступных игроку предметов. Выбор строки включает режим размещения —
/// сам спавн делает сервер по клику в мире.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DutySpawnMenuWindow : FancyWindow
{
    public event Action<string>? OnItemSelected;

    public DutySpawnMenuWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<DutySpawnMenuEntry> entries, float range)
    {
        ItemList.RemoveAllChildren();

        HintLabel.Text = Loc.GetString("duty-spawn-menu-hint", ("range", range));

        if (entries.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("duty-spawn-menu-empty");
            return;
        }

        StatusLabel.Text = string.Empty;

        foreach (var entry in entries)
        {
            var count = entry.Remaining < 0
                ? Loc.GetString("duty-spawn-menu-unlimited")
                : Loc.GetString("duty-spawn-menu-remaining", ("count", entry.Remaining));

            var button = new Button
            {
                Text = $"{entry.Name}  [{count}]",
                HorizontalExpand = true,
                Disabled = entry.Remaining == 0,
                ToolTip = entry.Proto,
            };

            var proto = entry.Proto;
            button.OnPressed += _ => OnItemSelected?.Invoke(proto);

            ItemList.AddChild(button);
        }
    }
}
