using System.Linq;
using Content.Client.Administration.Managers;
using Content.Client.Administration.UI.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminTab : Control
    {
        // _Duty-start: заголовок группы виден, только если в ней есть хоть одна доступная кнопка
        private readonly IClientAdminManager _admin;

        public AdminTab()
        {
            RobustXamlLoader.Load(this);
            _admin = IoCManager.Resolve<IClientAdminManager>();
            _admin.AdminStatusUpdated += UpdateGroups;
            UpdateGroups();
        }

        private void UpdateGroups()
        {
            UpdateGroup(PlayersHeader, PlayersGroup);
            UpdateGroup(ChatHeader, ChatGroup);
            UpdateGroup(ToolsHeader, ToolsGroup);
        }

        private static void UpdateGroup(Label header, GridContainer group)
        {
            var any = group.Children.OfType<CommandButton>().Any(b => b.IsAllowed);
            header.Visible = any;
            group.Visible = any;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
                _admin.AdminStatusUpdated -= UpdateGroups;
        }
        // _Duty-end
    }
}
