using System.Linq;
using Content.Shared.Body;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;
    private bool _inTree;

    // _Duty: вкладки органов переиспользуются между перестройками, чтобы не терять поиск, скролл и выбранную вкладку.
    private readonly Dictionary<ProtoId<OrganCategoryPrototype>, OrganMarkingPicker> _organPickers = new();

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        if (_markingsModel == model)
            return;

        // _Duty: раньше подписка шла и здесь, и в EnteredTree (двойная перестройка, утечка при повторном SetModel).
        if (_inTree)
            Unsubscribe();

        _markingsModel = model;
        _organPickers.Clear();
        OrganTabs.RemoveAllChildren();

        if (_inTree)
            Subscribe();

        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _inTree = true; // _Duty: переработка пикера
        Subscribe();

        // Пока контрол был вне дерева, события мы не получали.
        UpdateMarkings();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _inTree = false; // _Duty: переработка пикера
        Unsubscribe();
    }

    private void Subscribe()
    {
        if (_markingsModel is null)
            return;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    private void Unsubscribe()
    {
        if (_markingsModel is null)
            return;

        _markingsModel.OrganDataChanged -= UpdateMarkings;
        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
    }

    private void OnOrganProfileDataChanged(bool refresh)
    {
        // Данные профиля (пол, набор органов) могут прийти после данных органов — тогда вкладки появятся только здесь.
        if (refresh)
            UpdateMarkings();
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        var desired = new List<(ProtoId<OrganCategoryPrototype> Organ, OrganMarkingPicker Control)>(); // _Duty: переработка пикера
        var seen = new HashSet<ProtoId<OrganCategoryPrototype>>();

        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            seen.Add(organ); // _Duty: переработка пикера

            // Переиспользуем вкладку, только если у органа те же слои и группа.
            if (!_organPickers.TryGetValue(organ, out var control) || !control.Matches(organData.Layers, organData.Group))
            {
                control = new OrganMarkingPicker(_markingsModel, organ, organData.Layers, organData.Group);
                _organPickers[organ] = control;
            }

            control.Refresh();

            if (control.Empty)
                continue;

            desired.Add((organ, control)); // _Duty: переработка пикера
        }

        foreach (var gone in _organPickers.Keys.Where(it => !seen.Contains(it)).ToList())
        {
            _organPickers.Remove(gone);
        }

        var current = OrganTabs.Children.OfType<OrganMarkingPicker>().ToList();
        var unchanged = current.Count == desired.Count;
        for (var j = 0; unchanged && j < current.Count; j++)
        {
            unchanged = ReferenceEquals(current[j], desired[j].Control);
        }

        if (!unchanged)
        {
            var currentTab = OrganTabs.CurrentTab;
            var previouslySelected = currentTab >= 0 && currentTab < current.Count ? current[currentTab] : null;

            OrganTabs.RemoveAllChildren();
            foreach (var (_, control) in desired)
            {
                OrganTabs.AddChild(control);
            }

            if (desired.Count > 0)
            {
                var restored = desired.FindIndex(it => ReferenceEquals(it.Control, previouslySelected));
                OrganTabs.CurrentTab = restored >= 0 ? restored : 0;
            }
        }

        for (var i = 0; i < desired.Count; i++)
        {
            OrganTabs.SetTabTitle(i, Loc.TryGetString($"markings-organ-{desired[i].Organ.Id}", out var title) ? title : desired[i].Organ.Id);
        }

        OrganTabs.TabsVisible = desired.Count > 1;
    }
}
