using System.Linq;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

// _Duty-start: переработка пикера (переиспользование контролов, секция «Выбрано»)

[GenerateTypedNameReferences]
public sealed partial class OrganMarkingPicker : Control
{
    [Dependency] private readonly MarkingManager _marking = default!;
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly HashSet<HumanoidVisualLayers> _layers;
    private readonly ProtoId<MarkingsGroupPrototype> _group;
    private readonly ProtoId<OrganCategoryPrototype> _organ;
    private readonly Dictionary<HumanoidVisualLayers, LayerMarkingPicker> _layerPickers = new(); // _Duty

    public OrganMarkingPicker(MarkingsViewModel markingsModel, ProtoId<OrganCategoryPrototype> organ, HashSet<HumanoidVisualLayers> layers, ProtoId<MarkingsGroupPrototype> group)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _markingsModel = markingsModel;
        _layers = new HashSet<HumanoidVisualLayers>(layers); // _Duty: копия, чтобы Matches не зависел от внешних правок
        _group = group;
        _organ = organ;

        _sprite = _entity.System<SpriteSystem>();

        Refresh();
    }

    public bool Empty => LayerTabs.ChildCount == 0;

    /// <summary>
    /// Совпадают ли слои и группа с теми, для которых создан этот пикер (иначе его надо пересоздать).
    /// </summary>
    public bool Matches(HashSet<HumanoidVisualLayers> layers, ProtoId<MarkingsGroupPrototype> group)
    {
        return _group == group && _layers.SetEquals(layers);
    }

    /// <summary>
    /// Обновляет набор доступных маркингов на месте: пикеры слоёв переиспользуются,
    /// поэтому текст поиска, скролл и выбранная вкладка не теряются.
    /// </summary>
    public void Refresh()
    {
        // _Duty: раньше здесь был RemoveAllChildren + пересоздание всех слоёв.
        if (!_markingsModel.OrganProfileData.TryGetValue(_organ, out var organProfileData))
            return;

        var desired = new List<(HumanoidVisualLayers Layer, LayerMarkingPicker Control)>();

        // OrderBy: порядок слоёв стабильный, а не зависит от порядка внутри HashSet.
        foreach (var layer in _layers.OrderBy(it => (int) it))
        {
            var allMarkings =
                _markingsModel.EnforceGroupAndSexRestrictions ? _marking.MarkingsByLayerAndGroupAndSex(layer, _group, organProfileData.Sex) : _marking.MarkingsByLayer(layer);

            if (allMarkings.Count == 0)
                continue;

            if (_layerPickers.TryGetValue(layer, out var picker))
                picker.SetMarkings(allMarkings);
            else
                _layerPickers[layer] = picker = new LayerMarkingPicker(_markingsModel, _organ, layer, allMarkings);

            desired.Add((layer, picker));
        }

        var current = LayerTabs.Children.OfType<LayerMarkingPicker>().ToList();
        var unchanged = current.Count == desired.Count;
        for (var j = 0; unchanged && j < current.Count; j++)
        {
            unchanged = ReferenceEquals(current[j], desired[j].Control);
        }

        if (!unchanged)
        {
            var currentTab = LayerTabs.CurrentTab;
            var previouslySelected = currentTab >= 0 && currentTab < current.Count ? current[currentTab] : null;

            LayerTabs.RemoveAllChildren();
            foreach (var (_, control) in desired)
            {
                LayerTabs.AddChild(control);
            }

            if (desired.Count > 0)
            {
                var restored = desired.FindIndex(it => ReferenceEquals(it.Control, previouslySelected));
                LayerTabs.CurrentTab = restored >= 0 ? restored : 0;
            }
        }

        for (var i = 0; i < desired.Count; i++)
        {
            var layer = desired[i].Layer;
            if (Loc.TryGetString($"markings-layer-{layer}-{_group.Id}", out var layerTitle))
                LayerTabs.SetTabTitle(i, layerTitle);
            else if (Loc.TryGetString($"markings-layer-{layer}", out var baseTitle))
                LayerTabs.SetTabTitle(i, baseTitle);
            else
                LayerTabs.SetTabTitle(i, layer.ToString());
        }

        LayerTabs.TabsVisible = desired.Count > 1;
    }
}
// _Duty-end
