using System.Linq;
using System.Numerics;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatLookupView : PanelContainer
{
    private NanoChatUiState? _lastState;
    private string _filter = string.Empty;

    public NanoChatLookupView()
    {
        RobustXamlLoader.Load(this);

        SearchInput.OnTextChanged += args =>
        {
            _filter = args.Text.Trim();
            RenderList();
        };
    }
    public event Action<NanoChatRecipient>? OnStartChat;

    public void UpdateContactList(NanoChatUiState state)
    {
        _lastState = state;
        RenderList();
    }

    private void RenderList()
    {
        ContactsList.RemoveAllChildren();
        if (_lastState is not { } state || state.Contacts is not { } allContacts)
        {
            ContactsList.AddChild(new Label() { Text = Loc.GetString("nano-chat-look-up-no-server") });
            return;
        }

        var contacts = string.IsNullOrEmpty(_filter)
            ? allContacts
            : allContacts.Where(c =>
                    c.Name.Contains(_filter, StringComparison.CurrentCultureIgnoreCase) ||
                    c.Number.ToString("D4").Contains(_filter))
                .ToList();

        for (var idx = 0; idx < contacts.Count; idx++)
        {
            var contact = contacts[idx];
            var nameLabel = new Label()
            {
                Text = contact.Name,
                HorizontalAlignment = HAlignment.Left,
                HorizontalExpand = true
            };
            var numberLabel = new Label()
            {
                Text = $"#{contacts[idx].Number:D4}",
                HorizontalAlignment = HAlignment.Right,
                Margin = new Thickness(0, 0, 36, 0),
            };
            var startChatButton = new Button()
            {
                Text = "+",
                HorizontalAlignment = HAlignment.Right,
                MinSize = new Vector2(32, 32),
                MaxSize = new Vector2(32, 32),
                ToolTip = Loc.GetString("nano-chat-new-chat"),
            };
            startChatButton.AddStyleClass("OpenBoth");
            if (contact.Number == state.OwnNumber || state.Recipients.ContainsKey(contact.Number) || state.MaxRecipients <= state.Recipients.Count)
            {
                startChatButton.Disabled = true;
            }
            startChatButton.OnPressed += _ => OnStartChat?.Invoke(contact);

            var panel = new PanelContainer()
            {
                HorizontalExpand = true,
            };

            panel.AddChild(nameLabel);
            panel.AddChild(numberLabel);
            panel.AddChild(startChatButton);

            var styleClass = idx % 2 == 0 ? "PanelBackgroundBaseDark" : "PanelBackgroundLight";
            panel.StyleClasses.Add(styleClass);

            ContactsList.AddChild(panel);
        }
    }
}
