using System.Linq;
using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Animations;
using Robust.Shared.Timing;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    // How often we're willing to ping the recipient that we're typing, while typing.
    private static readonly TimeSpan TypingPingInterval = TimeSpan.FromSeconds(2);
    private const int PreviewMaxLength = 28;
    private const string TypingFadeAnimationKey = "nano-chat-typing-fade";

    private static readonly Animation TypingFadeIn = new()
    {
        Length = TimeSpan.FromSeconds(0.12),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = "Modulate",
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White.WithAlpha(0f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.12f),
                },
            },
        },
    };

    private readonly ClientGameTicker _gameTicker;
    private readonly NewChatPopup _newChatPopup;
    private readonly NewGroupChatPopup _newGroupChatPopup;
    private uint? _currentChat;
    private uint? _pendingChat;
    private uint _ownNumber;
    private bool _notificationsMuted;
    private bool _listNumber = true;
    private Dictionary<uint, NanoChatRecipient> _recipients = new();
    private Dictionary<uint, List<NanoChatMessage>> _messages = new();
    private TimeSpan _lastTypingSent = TimeSpan.Zero;

    // Track what the client has already rendered so the enter animation only plays for
    // content that's genuinely new, not for every bubble/entry on every state refresh.
    private readonly HashSet<uint> _knownRecipients = new();
    private readonly Dictionary<uint, int> _lastMessageCounts = new();
    private bool _chatListInitialized;

    public event Action<NanoChatUiMessageType, uint?, string?, string?, List<uint>?>? OnMessageSent;

    public NanoChatUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        _newChatPopup = new NewChatPopup();
        _newGroupChatPopup = new NewGroupChatPopup();
        SetupEventHandlers();
    }

    private void SetupEventHandlers()
    {
        _newChatPopup.OnChatCreated += (number, name, job) =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.NewChat, number, name, job, null);
        };

        NewChatButton.OnPressed += _ =>
        {
            _newChatPopup.ClearInputs();
            _newChatPopup.OpenCentered();
        };

        _newGroupChatPopup.OnGroupCreated += (name, members) =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.NewGroupChat, null, name, null, members);
        };

        NewGroupChatButton.OnPressed += _ =>
        {
            _newGroupChatPopup.ClearInputs();
            _newGroupChatPopup.OpenCentered();
        };

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleMute, null, null, null, null);
        };

        MessageInput.OnTextChanged += args =>
        {
            var length = args.Text.Length;
            var activeChat = _pendingChat ?? _currentChat;
            var isValid = !string.IsNullOrWhiteSpace(args.Text) &&
                          length <= NanoChatMessage.MaxContentLength &&
                          activeChat != null;

            SendButton.Disabled = !isValid;

            // Show character count when over limit
            CharacterCount.Visible = length > NanoChatMessage.MaxContentLength;
            if (length > NanoChatMessage.MaxContentLength)
            {
                CharacterCount.Text = Loc.GetString("nano-chat-message-too-long",
                    ("current", length),
                    ("max", NanoChatMessage.MaxContentLength));
                CharacterCount.StyleClasses.Add("LabelDanger");
            }

            // Let the other side know we're typing, throttled so we're not pinging the
            // server on every keystroke.
            if (isValid && activeChat != null && _timing.CurTime - _lastTypingSent >= TypingPingInterval)
            {
                _lastTypingSent = _timing.CurTime;
                OnMessageSent?.Invoke(NanoChatUiMessageType.Typing, activeChat, null, null, null);
            }
        };

        LookupButton.OnPressed += _ => ToggleView();
        LookupView.OnStartChat += contact =>
        {
            if (OnMessageSent is { } handler)
            {
                handler(NanoChatUiMessageType.NewChat, contact.Number, contact.Name, contact.JobTitle, null);
                SelectChat(contact.Number);
                ToggleView();
            }
        };
        ListNumberButton.OnPressed += _ =>
        {
            _listNumber = !_listNumber;
            UpdateListNumber();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleListNumber, null, null, null, null);
        };

        MessageInput.OnTextEntered += _ => SendMessage(); // Send message when pressing enter
        SendButton.OnPressed += _ => SendMessage();
        DeleteChatButton.OnPressed += _ => DeleteCurrentChat();
    }

    private void ToggleView()
    {
        ChatView.Visible = !ChatView.Visible;
        LookupView.Visible = !ChatView.Visible;
        LookupButton.Pressed = LookupView.Visible;
    }

    private void SendMessage()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null || string.IsNullOrWhiteSpace(MessageInput.Text))
            return;

        var messageContent = MessageInput.Text;
        if (!string.IsNullOrWhiteSpace(messageContent))
        {
            messageContent = messageContent.Trim();
            if (messageContent.Length > NanoChatMessage.MaxContentLength)
                messageContent = messageContent[..NanoChatMessage.MaxContentLength];
        }

        // Add predicted message
        var predictedMessage = new NanoChatMessage(
            _timing.CurTime,
            messageContent,
            _ownNumber
        );

        if (!_messages.TryGetValue(activeChat.Value, out var value))
        {
            value = new List<NanoChatMessage>();
            _messages[activeChat.Value] = value;
        }

        value.Add(predictedMessage);

        // Update UI with predicted message
        UpdateMessages(_messages);

        // Send message event
        OnMessageSent?.Invoke(NanoChatUiMessageType.SendMessage, activeChat, messageContent, null, null);

        // Clear input
        MessageInput.Text = string.Empty;
        SendButton.Disabled = true;
    }

    private void SelectChat(uint number)
    {
        // Don't reselect the same chat
        if (_currentChat == number && _pendingChat == null)
            return;

        _pendingChat = number;

        // Predict marking messages as read
        if (_recipients.TryGetValue(number, out var recipient))
        {
            recipient.HasUnread = false;
            _recipients[number] = recipient;
            UpdateChatList(_recipients, _messages);
        }

        OnMessageSent?.Invoke(NanoChatUiMessageType.SelectChat, number, null, null, null);
        UpdateCurrentChat();
    }

    private void DeleteCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null)
            return;

        OnMessageSent?.Invoke(NanoChatUiMessageType.DeleteChat, activeChat, null, null, null);
    }

    private void UpdateChatList(Dictionary<uint, NanoChatRecipient> recipients, Dictionary<uint, List<NanoChatMessage>> messages)
    {
        ChatList.RemoveAllChildren();
        _recipients = recipients;

        NoChatsLabel.Visible = recipients.Count == 0;
        if (NoChatsLabel.Parent != ChatList)
        {
            NoChatsLabel.Parent?.RemoveChild(NoChatsLabel);
            ChatList.AddChild(NoChatsLabel);
        }

        // Most recently active conversation first, like a real messenger - contacts with
        // no messages yet fall back to alphabetical at the bottom.
        var ordered = recipients
            .Select(kv => (Number: kv.Key,
                Recipient: kv.Value,
                LastMessage: messages.TryGetValue(kv.Key, out var msgs) && msgs.Count > 0 ? msgs[^1] : (NanoChatMessage?)null))
            .OrderByDescending(e => e.LastMessage?.Timestamp ?? TimeSpan.Zero)
            .ThenBy(e => e.Recipient.Name, StringComparer.Ordinal);

        foreach (var (number, recipient, lastMessage) in ordered)
        {
            var entry = new NanoChatEntry();
            // For pending chat selection, always show it as selected even if unconfirmed
            var isSelected = (_pendingChat == number) || (_pendingChat == null && _currentChat == number);

            string subtitle;
            string? timeText = null;
            if (lastMessage is { } message)
            {
                var prefix = message.SenderId == _ownNumber ? Loc.GetString("nano-chat-preview-you") + " " : "";
                subtitle = prefix + TruncatePreview(message.Content);
                timeText = FormatMessageTime(message.Timestamp);
            }
            else if (recipient.IsGroup)
            {
                subtitle = Loc.GetString("nano-chat-group-members-subtitle", ("count", recipient.MemberCount));
            }
            else
            {
                subtitle = recipient.JobTitle ?? "";
            }

            entry.SetRecipient(recipient, number, isSelected, subtitle, timeText);
            entry.OnPressed += SelectChat;
            ChatList.AddChild(entry);

            // Skip the very first populate (opening the program) so the whole contact
            // list doesn't flash-fade at once - only genuinely new contacts animate.
            if (_chatListInitialized && !_knownRecipients.Contains(number))
                entry.PlayEnterAnimation();
        }

        _chatListInitialized = true;
        _knownRecipients.Clear();
        foreach (var number in recipients.Keys)
            _knownRecipients.Add(number);
    }

    private static string TruncatePreview(string text)
    {
        return text.Length <= PreviewMaxLength ? text : text[..PreviewMaxLength] + "…";
    }

    private string FormatMessageTime(TimeSpan timestamp)
    {
        var stationTime = timestamp - _gameTicker.RoundStartTimeSpan;
        if (stationTime < TimeSpan.Zero)
            stationTime = TimeSpan.Zero;

        return stationTime.ToString(@"hh\:mm");
    }

    private void UpdateCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        var hasActiveChat = activeChat != null;

        // Update UI state
        MessagesScroll.Visible = hasActiveChat;
        CurrentChatName.Visible = !hasActiveChat;
        MessageInputContainer.Visible = hasActiveChat;
        DeleteChatButton.Visible = hasActiveChat;
        DeleteChatButton.Disabled = !hasActiveChat;

        if (activeChat != null && _recipients.TryGetValue(activeChat.Value, out var recipient))
        {
            CurrentChatName.Text = recipient.Name + (string.IsNullOrEmpty(recipient.JobTitle) ? "" : $" ({recipient.JobTitle})");
        }
        else
        {
            CurrentChatName.Text = Loc.GetString("nano-chat-select-chat");
        }
    }

    private void UpdateMessages(Dictionary<uint, List<NanoChatMessage>> messages)
    {
        _messages = messages;
        MessageList.RemoveAllChildren();

        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null || !messages.TryGetValue(activeChat.Value, out var chatMessages))
            return;

        // First time seeing this chat's history: show it all instantly, don't fade in
        // the whole backlog. Only messages appended after that count as new.
        if (!_lastMessageCounts.TryGetValue(activeChat.Value, out var previousCount))
            previousCount = chatMessages.Count;

        var isGroupChat = _recipients.TryGetValue(activeChat.Value, out var activeRecipient) && activeRecipient.IsGroup;

        for (var i = 0; i < chatMessages.Count; i++)
        {
            var message = chatMessages[i];
            var messageBubble = new NanoChatMessageBubble();
            messageBubble.SetMessage(message, message.SenderId == _ownNumber, isGroupChat);
            MessageList.AddChild(messageBubble);

            if (i >= previousCount)
                messageBubble.PlayEnterAnimation();

            // Add spacing between messages
            MessageList.AddChild(new Control { MinSize = new Vector2(0, 4) });
        }

        _lastMessageCounts[activeChat.Value] = chatMessages.Count;

        MessageList.InvalidateMeasure();
        MessagesScroll.InvalidateMeasure();

        // Scroll to bottom after messages are added
        if (MessageList.Parent is ScrollContainer scroll)
            scroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    private void UpdateMuteButton()
    {
        if (BellMutedIcon != null)
            BellMutedIcon.Visible = _notificationsMuted;
    }

    private void UpdateListNumber()
    {
        if (ListNumberButton != null)
            ListNumberButton.Pressed = _listNumber;
    }

    public void UpdateState(NanoChatUiState state)
    {
        _ownNumber = state.OwnNumber;
        _notificationsMuted = state.NotificationsMuted;
        _listNumber = state.ListNumber;
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";
        UpdateMuteButton();
        UpdateListNumber();

        // Update new chat button state based on recipient limit
        var atLimit = state.Recipients.Count >= state.MaxRecipients;
        NewChatButton.Disabled = atLimit;
        NewChatButton.ToolTip = atLimit
            ? Loc.GetString("nano-chat-max-recipients")
            : Loc.GetString("nano-chat-new-chat");

        // First handle pending chat resolution if we have one
        if (_pendingChat != null)
        {
            // Only reconcile once the server confirms the specific chat we asked for.
            // A state push can arrive for an unrelated reason (e.g. someone else's
            // message came in) before our SelectChat is processed - if we synced
            // _currentChat to that stale state unconditionally, the view would flash
            // back to the previous chat mid-switch. Keep predicting our own pick until
            // the server actually agrees with it.
            if (_pendingChat == state.CurrentChat)
            {
                _currentChat = _pendingChat;
                _pendingChat = null;
            }
        }
        else
        {
            _currentChat = state.CurrentChat;
        }

        UpdateCurrentChat();
        UpdateChatList(state.Recipients, state.Messages);
        UpdateMessages(state.Messages);
        UpdateTypingIndicator(state.TypingFrom);
        LookupView.UpdateContactList(state);
    }

    private void UpdateTypingIndicator(uint? typingFrom)
    {
        var activeChat = _pendingChat ?? _currentChat;
        var isTyping = typingFrom != null && typingFrom == activeChat;

        if (isTyping == TypingIndicatorLabel.Visible)
            return;

        if (isTyping)
        {
            if (_recipients.TryGetValue(typingFrom!.Value, out var recipient))
                TypingIndicatorLabel.Text = Loc.GetString("nano-chat-typing", ("name", recipient.Name));

            TypingIndicatorLabel.Visible = true;
            TypingIndicatorLabel.PlayAnimation(TypingFadeIn, TypingFadeAnimationKey);
        }
        else
        {
            TypingIndicatorLabel.Visible = false;
        }
    }
}