using System;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Utility;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageBubble : BoxContainer
{
    public static readonly Color OwnMessageColor = Color.FromHex("#173717d9"); // Dark green
    public static readonly Color OtherMessageColor = Color.FromHex("#252525d9"); // Dark gray
    public static readonly Color BorderColor = Color.FromHex("#40404066"); // Subtle border
    public static readonly Color TextColor = Color.FromHex("#dcdcdc"); // Slightly softened white
    public static readonly Color ErrorColor = Color.FromHex("#cc3333"); // Red

    private const string EnterAnimationKey = "nano-chat-bubble-enter";

    private static readonly Animation EnterAnimation = new()
    {
        Length = TimeSpan.FromSeconds(0.12),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White.WithAlpha(0f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.12f),
                },
            },
        },
    };

    public NanoChatMessageBubble()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    ///     Plays a quick fade-in - used only for genuinely new messages, not for every
    ///     bubble on a full list rebuild, so the chat doesn't flicker on every update.
    /// </summary>
    public void PlayEnterAnimation()
    {
        PlayAnimation(EnterAnimation, EnterAnimationKey);
    }

    public void SetMessage(NanoChatMessage message, bool isOwnMessage, bool showSenderName = false)
    {
        if (MessagePanel.PanelOverride is not StyleBoxFlat)
            return;

        // Configure message appearance
        var style = (StyleBoxFlat)MessagePanel.PanelOverride;
        style.BackgroundColor = isOwnMessage ? OwnMessageColor : OtherMessageColor;
        style.BorderColor = BorderColor;

        // Group chats only - who actually sent this one, never shown for our own messages
        SenderNameLabel.Visible = showSenderName && !isOwnMessage && !string.IsNullOrEmpty(message.SenderName);
        if (SenderNameLabel.Visible)
            SenderNameLabel.Text = message.SenderName;

        // Set message content
        MessageText.Text = FormattedMessage.EscapeText(message.Content);;
        MessageText.Modulate = TextColor;

        // Show delivery status for own messages only
        DeliveryFailedLabel.Visible = isOwnMessage && message.DeliveryFailed;
        if (DeliveryFailedLabel.Visible)
            DeliveryFailedLabel.Modulate = ErrorColor;

        DeliveredLabel.Visible = isOwnMessage && !message.DeliveryFailed;

        // For own messages: FlexSpace -> MessagePanel -> RightSpacer
        // For other messages: LeftSpacer -> MessagePanel -> FlexSpace
        MessageContainer.RemoveAllChildren();

        // fuuuuuck
        MessageBox.Parent?.RemoveChild(MessageBox);

        if (isOwnMessage)
        {
            MessageContainer.AddChild(FlexSpace);
            MessageContainer.AddChild(MessageBox);
            MessageContainer.AddChild(RightSpacer);
        }
        else
        {
            MessageContainer.AddChild(LeftSpacer);
            MessageContainer.AddChild(MessageBox);
            MessageContainer.AddChild(FlexSpace);
        }
    }
}
