using System;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEntry : BoxContainer
{
    public event Action<uint>? OnPressed;
    private uint _number;
    private Action<EventArgs>? _pressHandler;

    private const string EnterAnimationKey = "nano-chat-entry-enter";

    private static readonly Animation EnterAnimation = new()
    {
        Length = TimeSpan.FromSeconds(0.12),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White.WithAlpha(0f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.12f),
                },
            },
        },
    };

    public NanoChatEntry()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    ///     Plays a quick fade-in - used only when a brand new contact shows up in the
    ///     list, not on every rebuild (the list is rebuilt on every state push).
    /// </summary>
    public void PlayEnterAnimation()
    {
        PlayAnimation(EnterAnimation, EnterAnimationKey);
    }

    public void SetRecipient(NanoChatRecipient recipient, uint number, bool isSelected, string subtitle, string? timeText)
    {
        // Remove old handler if it exists
        if (_pressHandler != null)
            ChatButton.OnPressed -= _pressHandler;

        _number = number;

        // Create and store new handler
        _pressHandler = _ => OnPressed?.Invoke(_number);
        ChatButton.OnPressed += _pressHandler;

        NameLabel.Text = recipient.Name;
        TimeLabel.Text = timeText ?? "";
        SubtitleLabel.Text = subtitle;
        SubtitleLabel.Visible = !string.IsNullOrEmpty(subtitle);
        UnreadIndicator.Visible = recipient.HasUnread;

        ChatButton.ModulateSelfOverride = isSelected ? NanoChatMessageBubble.OwnMessageColor : null;
    }
}
