using System.Linq;
using System.Text.RegularExpressions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NewGroupChatPopup : DefaultWindow
{
    private const int MaxNameLength = 32;
    private static readonly Regex NumberSplit = new(@"[^\d]+", RegexOptions.Compiled);

    public event Action<string, List<uint>>? OnGroupCreated;

    public NewGroupChatPopup()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(3);

        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => CreateGroup();

        NameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxNameLength)
                NameInput.Text = args.Text[..MaxNameLength];
            Validate();
        };

        MembersInput.OnTextChanged += _ => Validate();
    }

    private List<uint> ParseMembers()
    {
        return NumberSplit.Split(MembersInput.Text)
            .Where(s => s.Length > 0)
            .Select(s => uint.TryParse(s, out var number) ? (uint?)number : null)
            .Where(n => n != null)
            .Select(n => n!.Value)
            .Distinct()
            .ToList();
    }

    private void Validate()
    {
        var members = ParseMembers();
        MembersHintLabel.Text = Loc.GetString("nano-chat-group-members-count", ("count", members.Count));

        CreateButton.Disabled = string.IsNullOrWhiteSpace(NameInput.Text) || members.Count == 0;
    }

    private void CreateGroup()
    {
        var members = ParseMembers();
        if (members.Count == 0 || string.IsNullOrWhiteSpace(NameInput.Text))
            return;

        OnGroupCreated?.Invoke(NameInput.Text.Trim(), members);
        Close();
    }

    public void ClearInputs()
    {
        NameInput.Text = string.Empty;
        MembersInput.Text = string.Empty;
        Validate();
    }
}
