using System.Numerics;
using Content.Client._Duty.Construction;
using Content.Client.UserInterface.Controls;
using Content.Shared.Construction.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Construction.UI
{
    /// <summary>
    /// This is the interface for a UI View of the construction window. The point of it is to abstract away the actual
    /// UI controls and just provide higher level operations on the entire window. This View is completely passive and
    /// just raises events to the outside world. This class is controlled by the <see cref="ConstructionMenuPresenter"/>.
    /// </summary>
    public interface IConstructionMenuView : IDisposable
    {
        // It isn't optimal to expose UI controls like this, but the UI control design is
        // questionable so it can't be helped.

        bool EraseButtonPressed { get; set; }
        bool GridViewButtonPressed { get; set; }
        bool BuildButtonPressed { get; set; }

        ListContainer Recipes { get; }
        ItemList RecipeStepList { get; }


        ScrollContainer RecipesGridScrollContainer { get; }
        GridContainer RecipesGrid { get; }

        #region _Duty

        /// <summary>
        /// Боковая панель избранного справа от меню.
        /// </summary>
        FavoritesPanel FavoritesSidePanel { get; }

        /// <summary>
        /// Текст в строке поиска.
        /// </summary>
        string SearchText { get; }

        /// <summary>
        /// Выбранная в сайдбаре категория, либо <c>null</c>, если фильтр снят.
        /// </summary>
        string? SelectedCategory { get; }

        /// <summary>
        /// Перестроить сайдбар категорий. <paramref name="categories"/> идёт без псевдокатегории
        /// «Всё» — её добавляет сам сайдбар.
        /// </summary>
        void SetCategories(string allCategory, IReadOnlyList<string> categories, string? selected);

        /// <summary>
        /// Обновить кнопку-тумблер и видимость панели избранного.
        /// </summary>
        void SetFavoritesPanel(bool hasFavorites, int count, bool panelShown);

        /// <summary>
        /// Показать подсказку «в этой категории пусто, но в других есть».
        /// </summary>
        void ShowSearchHint(string category, int otherCount);

        void HideSearchHint();

        event EventHandler FavoritesPanelToggled;

        #endregion

        event EventHandler<(string search, string? category)> PopulateRecipes;
        event EventHandler<ConstructionMenu.ConstructionMenuListData?> RecipeSelected;
        event EventHandler RecipeFavorited;
        event EventHandler<bool> BuildButtonToggled;
        event EventHandler<bool> EraseButtonToggled;
        event EventHandler ClearAllGhosts;

        void ClearRecipeInfo();
        void SetRecipeInfo(string name, string description, EntityPrototype? targetPrototype, bool isItem, bool canAddToFavorites);
        void ResetPlacement();

        #region Window Control

        event Action? OnClose;

        bool IsOpen { get; }

        void OpenCentered();
        void MoveToFront();
        bool IsAtFront();
        void Close();

        #endregion
    }

    [GenerateTypedNameReferences]
    public sealed partial class ConstructionMenu : DefaultWindow, IConstructionMenuView
    {
        /// <summary>
        /// _Duty: ширина окна без панели избранного. Ширина панели прибавляется к ней при показе.
        /// </summary>
        private const float BaseWidth = 880f;

        private const float BaseHeight = 520f;

        /// <summary>
        /// Нижняя граница ручного ресайза. Подобрана так, чтобы инфо-колонке всегда хватало на
        /// её верхний тулбар: если растягивающемуся ребёнку не хватает доли до желаемой ширины,
        /// BoxContainer перестаёт его растягивать и отдаёт ему желаемую ширину целиком, отбирая
        /// место у соседей — именно так окно и начинало дёргаться.
        /// </summary>
        private const float BaseMinWidth = 820f;

        private const float BaseMinHeight = 380f;

        public bool BuildButtonPressed
        {
            get => BuildButton.Pressed;
            set => BuildButton.Pressed = value;
        }

        public bool EraseButtonPressed
        {
            get => EraseButton.Pressed;
            set => EraseButton.Pressed = value;
        }

        public bool GridViewButtonPressed
        {
            get => MenuGridViewButton.Pressed;
            set => MenuGridViewButton.Pressed = value;
        }

        public string SearchText => SearchBar.Text;

        public string? SelectedCategory => CategoryList.Selected;

        public ConstructionMenu()
        {
            SetSize = new Vector2(BaseWidth, BaseHeight);
            MinSize = new Vector2(BaseMinWidth, BaseMinHeight);

            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Title = Loc.GetString("construction-menu-title");

            BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
            Recipes.ItemPressed += (_, data) => RecipeSelected?.Invoke(this, data as ConstructionMenuListData);
            Recipes.NoItemSelected += () => RecipeSelected?.Invoke(this, null);
            Recipes.GenerateItem += (data, button) =>
            {
                if (data is not ConstructionMenuListData (var prototype, var targetPrototype))
                    return;

                var entProtoView = new EntityPrototypeView()
                {
                    SetSize = new(32f),
                    Stretch = SpriteView.StretchMode.Fill,
                    Scale = new(2),
                    Margin = new(0, 2),
                };
                entProtoView.SetPrototype(targetPrototype);

                var label = new Label()
                {
                    Text = prototype.Name,
                    Margin = new(5, 0),
                    // _Duty: ClipText обнуляет желаемую ширину метки, поэтому длинное название
                    // рецепта больше не раздвигает колонку и не перекраивает соседние.
                    ClipText = true,
                    HorizontalExpand = true,
                };

                var box = new BoxContainer();
                box.AddChild(entProtoView);
                box.AddChild(label);

                button.AddChild(box);
                // _Duty: название теперь может обрезаться, поэтому оно ушло в тултип.
                button.ToolTip = string.IsNullOrWhiteSpace(prototype.Description)
                    ? prototype.Name
                    : $"{prototype.Name}\n{prototype.Description}";
                button.AddStyleClass(ListContainer.StyleClassListContainerButton);
            };

            // _Duty: смена категории больше не затирает поиск — фильтры живут независимо.
            SearchBar.OnTextChanged += _ => RequestPopulate();
            CategoryList.OnCategorySelected += _ => RequestPopulate();

            SearchEverywhereButton.Text = Loc.GetString("construction-menu-search-everywhere");
            SearchEverywhereButton.OnPressed += _ =>
            {
                // Снимаем фильтр категории и оставляем запрос — тот же эффект, что и повторный
                // клик по активной категории в сайдбаре.
                CategoryList.SetSelected(null);
                RequestPopulate();
            };

            FavoritesPanelToggleButton.OnPressed += _ => FavoritesPanelToggled?.Invoke(this, EventArgs.Empty);

            BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
            BuildButton.OnToggled += args => BuildButtonToggled?.Invoke(this, args.Pressed);
            ClearButton.Text = Loc.GetString("construction-menu-clear-all");
            ClearButton.OnPressed += _ => ClearAllGhosts?.Invoke(this, EventArgs.Empty);
            EraseButton.Text = Loc.GetString("construction-menu-eraser-mode");
            EraseButton.OnToggled += args => EraseButtonToggled?.Invoke(this, args.Pressed);

            FavoriteButton.OnPressed += args => RecipeFavorited?.Invoke(this, EventArgs.Empty);

            MenuGridViewButton.OnPressed += _ => RequestPopulate();
        }

        public event EventHandler? ClearAllGhosts;
        public event EventHandler<(string search, string? category)>? PopulateRecipes;
        public event EventHandler<ConstructionMenuListData?>? RecipeSelected;
        public event EventHandler? RecipeFavorited;
        public event EventHandler<bool>? BuildButtonToggled;
        public event EventHandler<bool>? EraseButtonToggled;
        public event EventHandler? FavoritesPanelToggled;

        private void RequestPopulate()
        {
            PopulateRecipes?.Invoke(this, (SearchBar.Text, CategoryList.Selected));
        }

        public void SetCategories(string allCategory, IReadOnlyList<string> categories, string? selected)
        {
            CategoryList.Populate(allCategory, categories, selected);
        }

        public void SetFavoritesPanel(bool hasFavorites, int count, bool panelShown)
        {
            FavoritesPanelToggleButton.Visible = hasFavorites;
            FavoritesPanelToggleButton.Text = $"★ {count}";
            FavoritesPanelToggleButton.ToolTip = Loc.GetString(panelShown
                ? "construction-menu-favorites-panel-hide"
                : "construction-menu-favorites-panel-show");

            SetFavoritesPanelVisible(hasFavorites && panelShown);
        }

        /// <summary>
        /// Панель пристраивается справа: окно растёт вправо, его левый край и все колонки
        /// остаются на месте.
        /// </summary>
        private void SetFavoritesPanelVisible(bool visible)
        {
            if (FavoritesSidePanel.Visible == visible)
                return;

            FavoritesSidePanel.Visible = visible;

            var delta = visible ? FavoritesPanel.PanelWidth : -FavoritesPanel.PanelWidth;

            MinSize = new Vector2(MinSize.X + delta, MinSize.Y);

            var width = float.IsNaN(SetSize.X) ? Size.X : SetSize.X;
            SetWidth = width + delta;

            if (visible)
                KeepPanelOnScreen(width + delta);
        }

        /// <summary>
        /// Единственный случай, когда окно всё-таки двигается: если панель уехала бы за правый край
        /// экрана, сдвигаем окно влево ровно на величину переполнения — иначе до неё не добраться.
        /// </summary>
        private void KeepPanelOnScreen(float targetWidth)
        {
            if (Parent == null)
                return;

            var overflow = Position.X + targetWidth - Parent.Size.X;

            if (overflow <= 0)
                return;

            LayoutContainer.SetPosition(this, new Vector2(MathF.Max(0f, Position.X - overflow), Position.Y));
        }

        public void ShowSearchHint(string category, int otherCount)
        {
            SearchHintLabel.SetMessage(Loc.GetString(
                "construction-menu-search-empty-in-category",
                ("category", Loc.GetString(category)),
                ("count", otherCount)));

            SearchHintBox.Visible = true;
        }

        public void HideSearchHint()
        {
            SearchHintBox.Visible = false;
        }

        public void ResetPlacement()
        {
            BuildButton.Pressed = false;
            EraseButton.Pressed = false;
        }

        public void SetRecipeInfo(
            string name,
            string description,
            EntityPrototype? targetPrototype,
            bool isItem,
            bool canAddToFavorites)
        {
            BuildButton.Disabled = false;
            BuildButton.Text = Loc.GetString(isItem ? "construction-menu-place-ghost" : "construction-menu-craft");
            TargetName.SetMessage(name);
            TargetDesc.SetMessage(description);
            TargetTexture.SetPrototype(targetPrototype?.ID);
            FavoriteButton.Visible = true;
            FavoriteButton.Text = Loc.GetString(canAddToFavorites
                ? "construction-add-favorite-button"
                : "construction-remove-from-favorite-button");
        }

        public void ClearRecipeInfo()
        {
            BuildButton.Disabled = true;
            TargetName.SetMessage(string.Empty);
            TargetDesc.SetMessage(string.Empty);
            TargetTexture.SetPrototype(null);
            FavoriteButton.Visible = false;
            RecipeStepList.Clear();
        }

        public sealed record ConstructionMenuListData(ConstructionPrototype Prototype, EntityPrototype TargetPrototype) : ListData;
    }
}
