// SPDX-FileCopyrightText: 2026 LocalDuty <https://github.com/Bebranot/LocalDuty_Reserve>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Duty.Trauma.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Duty.Trauma.UI;

/// <summary>
/// _Duty: окно пошагового лечения артерии. Активна только кнопка текущего этапа; на этапе
/// затягивания жгута кнопка показывает прогресс. Пока идёт DoAfter — все кнопки заблокированы.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ArterialTreatmentWindow : FancyWindow
{
    public event Action<ArterialTreatmentStep>? OnStepPressed;

    public ArterialTreatmentWindow()
    {
        RobustXamlLoader.Load(this);

        PalmButton.OnPressed += _ => OnStepPressed?.Invoke(ArterialTreatmentStep.PalmPress);
        FingerButton.OnPressed += _ => OnStepPressed?.Invoke(ArterialTreatmentStep.FingerPress);
        TourniquetButton.OnPressed += _ => OnStepPressed?.Invoke(ArterialTreatmentStep.ApplyTourniquet);
        TightenButton.OnPressed += _ => OnStepPressed?.Invoke(ArterialTreatmentStep.TightenTourniquet);
    }

    public void Update(ArterialTreatmentBuiState state)
    {
        SetStepEnabled(PalmButton, state, ArterialTreatmentStep.PalmPress);
        SetStepEnabled(FingerButton, state, ArterialTreatmentStep.FingerPress);
        SetStepEnabled(TourniquetButton, state, ArterialTreatmentStep.ApplyTourniquet);
        SetStepEnabled(TightenButton, state, ArterialTreatmentStep.TightenTourniquet);

        TightenButton.Text = Loc.GetString(
            "trauma-arterial-step-tighten-progress",
            ("current", state.TightenProgress),
            ("total", state.TightenRequired));

        InfoLabel.SetMessage(Loc.GetString(state.CurrentStep == ArterialTreatmentStep.Done
            ? "trauma-arterial-info-done"
            : "trauma-arterial-info"));
    }

    private static void SetStepEnabled(Button button, ArterialTreatmentBuiState state, ArterialTreatmentStep step)
    {
        button.Disabled = state.Busy || state.CurrentStep != step;
    }
}
