using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Duty.Welcome;

/// <summary>
/// _Duty: окно приветствия/чейнджлога. Текст вкладок статичен и полностью берётся из
/// локализации — по сети едет только признак «новичок ли это» (см. <see cref="DutyWelcomeEui"/>).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DutyWelcomeWindow : FancyWindow
{
    public bool DontShowAgain => DontShowAgainCheckBox.Pressed;

    public DutyWelcomeWindow()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(NewTab, Loc.GetString("duty-welcome-tab-new"));
        TabContainer.SetTabTitle(MechanicsTab, Loc.GetString("duty-welcome-tab-mechanics"));
        TabContainer.SetTabTitle(RulesTab, Loc.GetString("duty-welcome-tab-rules"));

        NewLabel.SetMessage(BuildNewTabText());
        MechanicsLabel.SetMessage(BuildMechanicsTabText());
        RulesLabel.SetMessage(BuildRulesTabText());

        OkButton.OnPressed += _ => Close();
    }

    public void SetNewPlayer(bool isNewPlayer)
    {
        HeaderLabel.Text = Loc.GetString(isNewPlayer
            ? "duty-welcome-header-newplayer"
            : "duty-welcome-header-veteran");
    }

    // _Duty: string.Join с отдельными string-аргументами резолвится в .NET 10 BCL на
    // params ReadOnlySpan<string?>-перегрузку — компилятор сворачивает вызов в [InlineArray]
    // буфер, который запрещён сендбоксом клиента (см. /duty-sandbox). Явный string[] массив
    // форсирует старую, разрешённую перегрузку.
    private static string BuildNewTabText()
    {
        return string.Join("\n", new[]
        {
            Loc.GetString("duty-welcome-new-intro"),
            "",
            Loc.GetString("duty-welcome-new-item-code-alpha"),
            Loc.GetString("duty-welcome-new-item-block"),
            Loc.GetString("duty-welcome-new-item-trauma"),
            Loc.GetString("duty-welcome-new-item-shieldbash"),
            "",
            Loc.GetString("duty-welcome-new-item-outro"),
        });
    }

    private static string BuildMechanicsTabText()
    {
        return string.Join("\n", new[]
        {
            Loc.GetString("duty-welcome-mechanics-intro"),
            "",
            Loc.GetString("duty-welcome-mechanics-combat-title"),
            Loc.GetString("duty-welcome-mechanics-combat-block"),
            Loc.GetString("duty-welcome-mechanics-combat-shieldbash"),
            Loc.GetString("duty-welcome-mechanics-combat-halberd"),
            Loc.GetString("duty-welcome-mechanics-combat-morale"),
            "",
            Loc.GetString("duty-welcome-injury-title"),
            Loc.GetString("duty-welcome-injury-trauma"),
            Loc.GetString("duty-welcome-injury-concussion"),
            Loc.GetString("duty-welcome-injury-fireagony"),
            Loc.GetString("duty-welcome-injury-heartbeat"),
            Loc.GetString("duty-welcome-injury-lazarus"),
            "",
            Loc.GetString("duty-welcome-atmo-title"),
            Loc.GetString("duty-welcome-atmo-fargunshot"),
            Loc.GetString("duty-welcome-atmo-pocketplayer"),
            Loc.GetString("duty-welcome-atmo-phrases"),
            "",
            Loc.GetString("duty-welcome-special-title"),
            Loc.GetString("duty-welcome-special-secimplants"),
            Loc.GetString("duty-welcome-special-mech"),
            Loc.GetString("duty-welcome-special-stalker"),
        });
    }

    private static string BuildRulesTabText()
    {
        return string.Join("\n", new[]
        {
            Loc.GetString("duty-welcome-rules-intro"),
            "",
            Loc.GetString("duty-welcome-rules-item-metagame"),
            Loc.GetString("duty-welcome-rules-item-injury-rp"),
            Loc.GetString("duty-welcome-rules-item-newplayer"),
            Loc.GetString("duty-welcome-rules-item-report"),
        });
    }
}
