using System.Linq;
using Content.Client._Duty.Administration;
using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control, IAdminMenuCommandSource // _Duty: поиск F7 и права
    {
        [Dependency] private readonly IClientConsoleHost _console = default!;
        [Dependency] private readonly IClientAdminManager _admin = default!; // _Duty

        // _Duty: кнопка → команда; кнопки без права прячутся, поиск F7 их находит
        private readonly (BaseButton Button, string Command)[] _commands;

        public RoundTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            StartRound.OnPressed += _ => _console.ExecuteCommand("startround");
            EndRound.OnPressed += _ => _console.ExecuteCommand("endround");
            RestartRound.OnPressed += _ => _console.ExecuteCommand("restartround");
            RestartRoundNow.OnPressed += _ => _console.ExecuteCommand("restartroundnow");
            // ADT-Tweak-Start
            DelayStart.OnPressed += _ => _console.ExecuteCommand("delaystart");
            ReadyAll.OnPressed += _ => _console.ExecuteCommand("readyall");
            // ADT-Tweak-End

            // _Duty-start
            _commands = new (BaseButton, string)[]
            {
                (StartRound, "startround"),
                (EndRound, "endround"),
                (RestartRound, "restartround"),
                (RestartRoundNow, "restartroundnow"),
                (DelayStart, "delaystart"),
                (ReadyAll, "readyall"),
            };

            foreach (var (button, command) in _commands)
            {
                button.ToolTip = AdminNodeLookup.Tooltip(command);
            }

            _admin.AdminStatusUpdated += ApplyPermissions;
            ApplyPermissions();
            // _Duty-end
        }

        // _Duty-start
        public IEnumerable<(BaseButton Button, string Command, bool Confirm)> MenuCommands =>
            _commands.Select(c => (c.Button, c.Command, true));

        private void ApplyPermissions()
        {
            foreach (var (button, command) in _commands)
            {
                button.Visible = _admin.CanCommand(command);
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
                _admin.AdminStatusUpdated -= ApplyPermissions;
        }
        // _Duty-end
    }
}
