using Content.Client._Duty.Administration;
using Content.Client.Administration.Managers;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class ServerTab : Control, IAdminMenuCommandSource // _Duty: поиск F7 и права
    {
        [Dependency] private readonly IConfigurationManager _config = default!;
        [Dependency] private readonly IClientConsoleHost _console = default!;
        [Dependency] private readonly IClientAdminManager _admin = default!; // _Duty

        public ServerTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _config.OnValueChanged(CCVars.OocEnabled, OocEnabledChanged, true);
            _config.OnValueChanged(CCVars.LoocEnabled, LoocEnabledChanged, true);

            ServerShutdownButton.OnPressed += _ => _console.ExecuteCommand("shutdown");

            // _Duty-start: кнопка выключения видна только тем, кому команда доступна
            ServerShutdownButton.ToolTip = AdminNodeLookup.Tooltip("shutdown");
            _admin.AdminStatusUpdated += ApplyPermissions;
            ApplyPermissions();
            // _Duty-end
        }

        // _Duty-start
        public IEnumerable<(BaseButton Button, string Command, bool Confirm)> MenuCommands
        {
            get { yield return (ServerShutdownButton, "shutdown", true); }
        }

        private void ApplyPermissions()
        {
            ServerShutdownButton.Visible = _admin.CanCommand("shutdown");
        }
        // _Duty-end

        private void OocEnabledChanged(bool value)
        {
            SetOocButton.Pressed = value;
        }

        private void LoocEnabledChanged(bool value)
        {
            SetLoocButton.Pressed = value;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                _config.UnsubValueChanged(CCVars.OocEnabled, OocEnabledChanged);
                _config.UnsubValueChanged(CCVars.LoocEnabled, LoocEnabledChanged);
                _admin.AdminStatusUpdated -= ApplyPermissions; // _Duty
            }
        }
    }
}
