// SPDX-FileCopyrightText: 2025 LocalDuty <https://github.com/Bebranot/LocalDuty_Reserve>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.ADT.CCVar;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.ADT.Traits.UI;

// _Duty-start: вкладка черт переписана целиком

// _Duty: вкладка черт переписана: категории слева, карточки в центре, подробности и «Мой персонаж» справа.
// Состояние (выбранные черты, лимиты, причины отказа) считается из одного набора _selected, а не из контролов,
// поэтому один клик = один проход обновления без пересборки списка.
[GenerateTypedNameReferences]
public sealed partial class TraitsTab : BoxContainer
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly Content.Client.ADT.Sponsors.SponsorManager _adtSponsors = default!;
    [Dependency] private readonly Robust.Client.Player.IPlayerManager _players = default!;
    [Dependency] private readonly JobRequirementsManager _requirementsManager = default!;

    /// <summary>Выбор изменился по инициативе игрока (клик, сброс, потеря доступа к черте).</summary>
    public event Action<HashSet<ProtoId<TraitPrototype>>>? OnTraitsChanged;

    private const string SponsorTraitCategory = "ADTSponsorTraits";

    private enum TraitFilter
    {
        All,
        Available,
        Selected,
        Grants,
        Costs,
    }

    private sealed class Section
    {
        public required ProtoId<TraitCategoryPrototype> Id;
        public required TraitCategoryPrototype Proto;
        public required BoxContainer Root;
        public required Label Header;
        public required GridContainer Grid;
        public required Button CategoryButton;
        public readonly List<TraitCard> Cards = new();
    }

    private readonly Dictionary<ProtoId<TraitPrototype>, TraitCard> _cards = new();
    private readonly Dictionary<ProtoId<TraitCategoryPrototype>, Section> _sections = new();
    private readonly Dictionary<ProtoId<TraitPrototype>, string> _blocked = new();
    private readonly Dictionary<ProtoId<TraitPrototype>, string> _names = new();
    private readonly HashSet<ProtoId<TraitPrototype>> _selected = new();
    private readonly Dictionary<TraitFilter, Button> _filterButtons = new();
    private Button? _allCategoriesButton;

    private HumanoidCharacterProfile? _profile;
    private ProtoId<JobPrototype>? _jobId;
    private int _maxGlobalTraits;
    private int _maxGlobalPoints;
    private string _search = string.Empty;
    private TraitFilter _filter = TraitFilter.All;
    private ProtoId<TraitCategoryPrototype>? _categoryFilter;
    private ProtoId<TraitPrototype>? _detailsTrait;
    private bool _suppressEvent;

    public TraitsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += args =>
        {
            _search = args.Text.Trim().ToLowerInvariant();
            ClearSearchButton.Visible = _search.Length > 0;
            ApplyVisibility();
        };
        ClearSearchButton.OnPressed += _ =>
        {
            SearchBar.Clear();
            _search = string.Empty;
            ClearSearchButton.Visible = false;
            ApplyVisibility();
        };
        ResetTraitsButton.OnPressed += _ => ResetSelection();
        ListScroll.OnResized += UpdateGridColumns;

        _prototype.PrototypesReloaded += OnProtoReload;
        _adtSponsors.Updated += OnSponsorsUpdated;

        _cfg.OnValueChanged(SimpleStationCCVars.MaxTraitCount, OnMaxTraitCountChanged, true);
        _cfg.OnValueChanged(SimpleStationCCVars.MaxTraitPoints, OnMaxTraitPointsChanged, true);

        BuildFilters();
        BuildAll();
        ShowDetails(null);
        SetStatus(null);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _prototype.PrototypesReloaded -= OnProtoReload;
        _adtSponsors.Updated -= OnSponsorsUpdated;
        _cfg.UnsubValueChanged(SimpleStationCCVars.MaxTraitCount, OnMaxTraitCountChanged);
        _cfg.UnsubValueChanged(SimpleStationCCVars.MaxTraitPoints, OnMaxTraitPointsChanged);
    }

    #region Public API (используется HumanoidProfileEditor)

    public void RefreshTraits()
    {
        BuildAll();
    }

    /// <summary>
    /// Устанавливает выбранные черты (загрузка профиля). Событие изменения не вызывается.
    /// </summary>
    public void SetSelectedTraits(IEnumerable<ProtoId<TraitPrototype>> traits, HumanoidCharacterProfile? profile)
    {
        _profile = profile;

        _selected.Clear();
        foreach (var id in traits)
        {
            if (_prototype.HasIndex(id))
                _selected.Add(id);
        }

        var wasSuppressed = _suppressEvent;
        _suppressEvent = true;
        try
        {
            RecomputeBlocked();
            DropBlockedSelections();
        }
        finally
        {
            _suppressEvent = wasSuppressed;
        }

        RefreshAll();
    }

    /// <summary>
    /// Пересчитывает доступность черт для профиля (вид, должности, требования по времени игры).
    /// Если выбранная черта стала недоступной, она снимается и вызывается <see cref="OnTraitsChanged"/>.
    /// </summary>
    public void UpdateRequirements(HumanoidCharacterProfile? profile, ProtoId<JobPrototype>? jobId = null)
    {
        _profile = profile;
        _jobId = jobId;

        RecomputeBlocked();
        var changed = DropBlockedSelections();
        RefreshAll();

        if (changed && !_suppressEvent)
            OnTraitsChanged?.Invoke(_selected);
    }

    #endregion

    #region Построение

    private void OnMaxTraitCountChanged(int value)
    {
        _maxGlobalTraits = value;
        if (!Disposed)
            RefreshAll();
    }

    private void OnMaxTraitPointsChanged(int value)
    {
        _maxGlobalPoints = value;
        if (!Disposed)
            RefreshAll();
    }

    private void OnSponsorsUpdated()
    {
        if (Disposed)
            return;

        var lostSome = _selected.RemoveWhere(id => !IsTraitStillAvailable(id)) > 0;

        BuildAll();

        if (lostSome && !_suppressEvent)
            OnTraitsChanged?.Invoke(_selected);
    }

    private void OnProtoReload(PrototypesReloadedEventArgs args)
    {
        if (Disposed)
            return;

        if (args.WasModified<TraitPrototype>() || args.WasModified<TraitCategoryPrototype>())
            BuildAll();
    }

    private bool IsTraitStillAvailable(ProtoId<TraitPrototype> traitId)
    {
        if (!_prototype.TryIndex(traitId, out var trait))
            return false;

        return !trait.SponsorOnly || _adtSponsors.IsTraitAllowed(_players.LocalSession, traitId.Id);
    }

    private static ProtoId<TraitCategoryPrototype> GetCategoryId(TraitPrototype trait)
    {
        return trait.SponsorOnly ? new ProtoId<TraitCategoryPrototype>(SponsorTraitCategory) : trait.Category;
    }

    private string NameOf(TraitPrototype trait)
    {
        if (!_names.TryGetValue(trait.ID, out var name))
            _names[trait.ID] = name = Loc.GetString(trait.Name);

        return name;
    }

    private void BuildFilters()
    {
        var group = new ButtonGroup();
        void Add(TraitFilter filter, string loc)
        {
            var button = new Button
            {
                Text = Loc.GetString(loc),
                ToggleMode = true,
                Group = group,
                Pressed = filter == _filter,
            };
            button.OnPressed += _ =>
            {
                _filter = filter;
                ApplyVisibility();
            };
            _filterButtons[filter] = button;
            FilterRow.AddChild(button);
        }

        Add(TraitFilter.All, "duty-traits-filter-all");
        Add(TraitFilter.Available, "duty-traits-filter-available");
        Add(TraitFilter.Selected, "duty-traits-filter-selected");
        Add(TraitFilter.Grants, "duty-traits-filter-grants");
        Add(TraitFilter.Costs, "duty-traits-filter-costs");
    }

    /// <summary>
    /// Полностью строит списки категорий и карточек. Вызывается только при создании, перезагрузке прототипов и обновлении спонсорских данных.
    /// </summary>
    private void BuildAll()
    {
        TraitSections.RemoveAllChildren();
        CategoryList.RemoveAllChildren();
        _sections.Clear();
        _cards.Clear();
        _names.Clear();

        var categoryGroup = new ButtonGroup();

        _allCategoriesButton = new Button
        {
            ToggleMode = true,
            Group = categoryGroup,
            Pressed = _categoryFilter == null,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 3),
            ClipText = true,
        };
        _allCategoriesButton.OnPressed += _ =>
        {
            _categoryFilter = null;
            ApplyVisibility();
        };
        CategoryList.AddChild(_allCategoriesButton);

        var categories = _prototype.EnumeratePrototypes<TraitCategoryPrototype>()
            .OrderBy(c => c.Priority)
            .ThenBy(c => Loc.GetString(c.Name))
            .ToList();

        var traitsByCategory = _prototype.EnumeratePrototypes<TraitPrototype>()
            .Where(t => !t.SponsorOnly || _adtSponsors.IsTraitAllowed(_players.LocalSession, t.ID))
            .GroupBy(GetCategoryId)
            .ToDictionary(g => g.Key, g => g.OrderBy(NameOf, StringComparer.CurrentCultureIgnoreCase).ToList());

        foreach (var category in categories)
        {
            if (!traitsByCategory.TryGetValue(category.ID, out var traits) || traits.Count == 0)
                continue;

            var categoryId = new ProtoId<TraitCategoryPrototype>(category.ID);
            var accent = category.AccentColor;

            var header = new Label
            {
                Text = Loc.GetString(category.Name),
                ModulateSelfOverride = accent,
                StyleClasses = { "TraitsCategoryNameLabel" },
                Margin = new Thickness(2, 8, 0, 4),
            };
            var grid = new GridContainer { Columns = 2, HorizontalExpand = true, HSeparationOverride = 6 };
            var root = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
            root.AddChild(header);
            root.AddChild(grid);
            TraitSections.AddChild(root);

            var button = new Button
            {
                ToggleMode = true,
                Group = categoryGroup,
                Pressed = _categoryFilter == categoryId,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
                ClipText = true,
            };
            button.OnPressed += _ =>
            {
                _categoryFilter = categoryId;
                ApplyVisibility();
            };
            CategoryList.AddChild(button);

            var section = new Section
            {
                Id = categoryId,
                Proto = category,
                Root = root,
                Header = header,
                Grid = grid,
                CategoryButton = button,
            };
            _sections[categoryId] = section;

            foreach (var trait in traits)
            {
                var description = trait.Description is { } desc ? Loc.GetString(desc) : string.Empty;
                var card = new TraitCard(trait, NameOf(trait), description, accent);
                card.Clicked += OnCardClicked;
                card.Hovered += c => ShowDetails(c.TraitId);
                section.Cards.Add(card);
                _cards[trait.ID] = card;
                grid.AddChild(card);
            }
        }

        // Выбранные, которых больше нет (удалённый прототип), убираем.
        _selected.RemoveWhere(id => !_cards.ContainsKey(id));

        if (_categoryFilter is { } filter && !_sections.ContainsKey(filter))
        {
            _categoryFilter = null;
            _allCategoriesButton.Pressed = true;
        }

        RecomputeBlocked();
        UpdateGridColumns();
        RefreshAll();
    }

    private void UpdateGridColumns()
    {
        var columns = Math.Max(1, (int) (ListScroll.Width / 300f));
        foreach (var section in _sections.Values)
        {
            section.Grid.Columns = columns;
        }
    }

    #endregion

    #region Правила выбора

    private int PointsSpent()
    {
        var sum = 0;
        foreach (var id in _selected)
        {
            if (_prototype.TryIndex(id, out var trait))
                sum += trait.Cost;
        }

        return sum;
    }

    private (int Count, int Points) CategoryUsage(ProtoId<TraitCategoryPrototype> category)
    {
        var count = 0;
        var points = 0;
        foreach (var id in _selected)
        {
            if (!_prototype.TryIndex(id, out var trait) || trait.Category != category)
                continue;

            count++;
            points += trait.Cost;
        }

        return (count, points);
    }

    /// <summary>
    /// Можно ли сейчас взять черту. В <paramref name="reason"/> — краткая причина отказа (уже локализованная).
    /// </summary>
    private bool CanSelect(TraitPrototype trait, out string? reason)
    {
        reason = null;

        if (_blocked.TryGetValue(trait.ID, out var blockReason))
        {
            reason = blockReason;
            return false;
        }

        if (_selected.Count >= _maxGlobalTraits)
        {
            reason = Loc.GetString("duty-traits-reject-count", ("max", _maxGlobalTraits));
            return false;
        }

        if (PointsSpent() + trait.Cost > _maxGlobalPoints)
        {
            reason = Loc.GetString("duty-traits-reject-points", ("cost", trait.Cost), ("left", _maxGlobalPoints - PointsSpent()));
            return false;
        }

        if (_prototype.TryIndex(trait.Category, out var category))
        {
            var (count, points) = CategoryUsage(trait.Category);
            if (category.MaxTraits is { } maxTraits && count >= maxTraits)
            {
                reason = Loc.GetString("duty-traits-reject-category-count", ("category", Loc.GetString(category.Name)), ("max", maxTraits));
                return false;
            }

            if (category.MaxPoints is { } maxPoints && points + trait.Cost > maxPoints)
            {
                reason = Loc.GetString("duty-traits-reject-category-points", ("category", Loc.GetString(category.Name)), ("max", maxPoints));
                return false;
            }
        }

        // Конфликты проверяем в обе стороны (сервер делает так же).
        foreach (var selectedId in _selected)
        {
            if (!_prototype.TryIndex(selectedId, out var other))
                continue;

            if (trait.Conflicts.Contains(selectedId) || other.Conflicts.Contains(trait.ID))
            {
                reason = Loc.GetString("duty-traits-reject-conflict", ("trait", NameOf(other)));
                return false;
            }
        }

        // ADT: «Случайная зависимость» нельзя взять, если выбраны все три конкретные зависимости.
        if (trait.ID == "RandomAddiction")
        {
            var concrete = new[]
            {
                new ProtoId<TraitPrototype>("AlcoholicAddiction"),
                new ProtoId<TraitPrototype>("NicotineAddiction"),
                new ProtoId<TraitPrototype>("DrugAddiction"),
            };
            if (concrete.All(_selected.Contains))
            {
                reason = Loc.GetString("duty-traits-reject-random-addiction");
                return false;
            }
        }

        return true;
    }

    private bool CanDeselect(TraitPrototype trait, out string? reason)
    {
        reason = null;

        // Отрицательная цена даёт очки: снять такую черту можно, только если остальные выбранные ещё укладываются в лимит.
        if (PointsSpent() - trait.Cost > _maxGlobalPoints)
        {
            reason = Loc.GetString("duty-traits-reject-deselect", ("trait", NameOf(trait)));
            return false;
        }

        return true;
    }

    /// <summary>Пересчитывает причины недоступности (вид, должность, требования) для всех черт.</summary>
    private void RecomputeBlocked()
    {
        _blocked.Clear();

        foreach (var id in _cards.Keys)
        {
            if (!_prototype.TryIndex(id, out var trait))
                continue;

            var reason = GetBlockReason(trait);
            if (reason != null)
                _blocked[id] = reason;
        }
    }

    private string? GetBlockReason(TraitPrototype trait)
    {
        var profile = _profile;
        if (profile != null)
        {
            if (trait.SpeciesWhitelist.Count > 0 && !trait.SpeciesWhitelist.Contains(profile.Species))
            {
                return Loc.GetString("duty-traits-block-species-whitelist", ("species", SpeciesNames(trait.SpeciesWhitelist)));
            }

            if (trait.SpeciesBlacklist.Contains(profile.Species))
                return Loc.GetString("duty-traits-block-species-blacklist");

            var jobs = new List<ProtoId<JobPrototype>>();
            if (_jobId is { } jobId)
            {
                jobs.Add(jobId);
            }
            else
            {
                foreach (var (profileJob, priority) in profile.JobPriorities)
                {
                    if (priority is JobPriority.High or JobPriority.Medium)
                        jobs.Add(profileJob);
                }
            }

            if (jobs.Any(job => IsJobBlocked(trait, job)))
                return Loc.GetString("trait-job-unavailable");
        }

        if (!_requirementsManager.CheckRequirementsForNonRole(trait.Requirements, _players.LocalSession, profile, out var reason))
        {
            return reason is { } message
                ? message.ToMarkup() is { Length: > 0 } text ? FormattedMessage.RemoveMarkupPermissive(text) : Loc.GetString("duty-traits-block-requirements")
                : Loc.GetString("duty-traits-block-requirements");
        }

        return null;
    }

    private bool IsJobBlocked(TraitPrototype trait, ProtoId<JobPrototype> job)
    {
        if (trait.JobBlacklist.Contains(job))
            return true;

        if (trait.JobWhitelist.Count > 0 && !trait.JobWhitelist.Contains(job))
            return true;

        if (trait.DepartmentWhitelist.Count == 0 && trait.DepartmentBlacklist.Count == 0)
            return false;

        var departments = _prototype.EnumeratePrototypes<DepartmentPrototype>()
            .Where(d => d.Roles.Contains(job))
            .Select(d => new ProtoId<DepartmentPrototype>(d.ID))
            .ToList();

        if (trait.DepartmentWhitelist.Count > 0 && !departments.Any(trait.DepartmentWhitelist.Contains))
            return true;

        return trait.DepartmentBlacklist.Count > 0 && departments.Any(trait.DepartmentBlacklist.Contains);
    }

    private string SpeciesNames(IEnumerable<ProtoId<SpeciesPrototype>> ids)
    {
        return string.Join(", ", ids.Select(id => _prototype.TryIndex(id, out var species) ? Loc.GetString(species.Name) : id.Id));
    }

    /// <summary>Снимает выбранные черты, ставшие недоступными. Возвращает true, если что-то сняли.</summary>
    private bool DropBlockedSelections()
    {
        return _selected.RemoveWhere(_blocked.ContainsKey) > 0;
    }

    #endregion

    #region Действия

    private void OnCardClicked(TraitCard card)
    {
        ShowDetails(card.TraitId);

        if (!_prototype.TryIndex(card.TraitId, out var trait))
            return;

        if (_selected.Contains(trait.ID))
        {
            if (!CanDeselect(trait, out var reason))
            {
                SetStatus(reason, error: true);
                return;
            }

            _selected.Remove(trait.ID);
        }
        else
        {
            if (!CanSelect(trait, out var reason))
            {
                SetStatus(reason, error: true);
                return;
            }

            _selected.Add(trait.ID);
        }

        SetStatus(null);
        RefreshAll();
        OnTraitsChanged?.Invoke(_selected);
    }

    private void RemoveSelected(ProtoId<TraitPrototype> id)
    {
        if (!_prototype.TryIndex(id, out var trait))
            return;

        if (!CanDeselect(trait, out var reason))
        {
            SetStatus(reason, error: true);
            return;
        }

        _selected.Remove(id);
        SetStatus(null);
        RefreshAll();
        OnTraitsChanged?.Invoke(_selected);
    }

    private void ResetSelection()
    {
        if (_selected.Count == 0)
            return;

        _selected.Clear();
        SetStatus(null);
        RefreshAll();
        OnTraitsChanged?.Invoke(_selected);
    }

    private void SetStatus(string? text, bool error = false)
    {
        if (string.IsNullOrEmpty(text))
        {
            StatusLabel.Text = Loc.GetString("duty-traits-status-hint");
            StatusLabel.ModulateSelfOverride = null;
            return;
        }

        StatusLabel.Text = text;
        StatusLabel.ModulateSelfOverride = error ? Color.FromHex("#f87171") : null;
    }

    #endregion

    #region Обновление отображения

    /// <summary>Один проход: шапка, карточки, счётчики категорий, фильтры и список «Мой персонаж».</summary>
    private void RefreshAll()
    {
        if (Disposed)
            return;

        UpdateHeader();
        UpdateCards();
        UpdateCategoryButtons();
        UpdateSelectedList();
        ApplyVisibility();

        if (_detailsTrait is { } details)
            ShowDetails(details);
    }

    private void UpdateHeader()
    {
        GlobalTraitCountLabel.Text = Loc.GetString("duty-traits-header-count", ("count", _selected.Count), ("max", _maxGlobalTraits));

        var remaining = _maxGlobalPoints - PointsSpent();
        GlobalPointsLabel.Text = _maxGlobalPoints > 0
            ? Loc.GetString("duty-traits-header-points", ("left", remaining), ("max", _maxGlobalPoints))
            : Loc.GetString("duty-traits-header-balance", ("balance", remaining));

        // При лимите очков 0 полоска только вводила в заблуждение («0 / 0») — показываем её лишь когда есть что показывать.
        PointsBar.Visible = _maxGlobalPoints > 0;
        if (_maxGlobalPoints > 0)
            PointsBar.Value = Math.Clamp(remaining / (float) _maxGlobalPoints, 0f, 1f);
    }

    private void UpdateCards()
    {
        foreach (var (id, card) in _cards)
        {
            if (!_prototype.TryIndex(id, out var trait))
                continue;

            var selected = _selected.Contains(id);
            if (selected)
            {
                card.SetState(true, false, null);
                continue;
            }

            var canSelect = CanSelect(trait, out var reason);
            card.SetState(false, !canSelect, canSelect ? null : reason);
        }
    }

    private void UpdateCategoryButtons()
    {
        if (_allCategoriesButton != null)
        {
            _allCategoriesButton.Text = Loc.GetString("duty-traits-category-all", ("count", _selected.Count));
        }

        foreach (var section in _sections.Values)
        {
            var count = section.Cards.Count(card => _selected.Contains(card.TraitId));
            var suffix = section.Proto.MaxTraits is { } max
                ? Loc.GetString("trait-category-traits", ("selected", count), ("max", max))
                : count > 0 ? count.ToString() : string.Empty;

            var name = Loc.GetString(section.Proto.Name);
            section.CategoryButton.Text = suffix.Length > 0 ? $"{name}  [{suffix}]" : name;
        }
    }

    private void UpdateSelectedList()
    {
        SelectedList.RemoveAllChildren();

        if (_selected.Count == 0)
        {
            SelectedList.AddChild(new Label
            {
                Text = Loc.GetString("duty-traits-none-selected"),
                ModulateSelfOverride = Color.FromHex("#a0a0a0"),
            });
            return;
        }

        var ordered = _selected
            .Select(id => _prototype.TryIndex(id, out var trait) ? trait : null)
            .Where(trait => trait != null)
            .OrderBy(trait => _prototype.TryIndex(trait!.Category, out var c) ? c.Priority : 0)
            .ThenBy(trait => NameOf(trait!), StringComparer.CurrentCultureIgnoreCase);

        foreach (var trait in ordered)
        {
            var id = trait!.ID;
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 2) };

            var (costText, costColor) = TraitCard.FormatCost(trait.Cost);
            var name = new Label { Text = NameOf(trait), ClipText = true, HorizontalExpand = true };
            row.AddChild(name);
            row.AddChild(new Label { Text = costText, ModulateSelfOverride = costColor, Margin = new Thickness(6, 0) });

            var remove = new Button { Text = "✕", ToolTip = Loc.GetString("duty-traits-remove") };
            remove.OnPressed += _ => RemoveSelected(id);
            row.AddChild(remove);

            // Наведение на строку показывает подробности той же черты.
            name.MouseFilter = MouseFilterMode.Stop;
            name.OnMouseEntered += _ => ShowDetails(id);

            SelectedList.AddChild(row);
        }
    }

    /// <summary>Применяет поиск, фильтр и выбранную категорию без пересоздания контролов.</summary>
    private void ApplyVisibility()
    {
        foreach (var section in _sections.Values)
        {
            var sectionVisible = _categoryFilter == null || _categoryFilter == section.Id;
            var anyVisible = false;

            if (sectionVisible)
            {
                foreach (var card in section.Cards)
                {
                    var visible = MatchesSearch(card) && MatchesFilter(card);
                    card.Visible = visible;
                    anyVisible |= visible;
                }
            }

            section.Root.Visible = sectionVisible && anyVisible;
            // Заголовок категории нужен только в режиме «Все»: в одной категории он дублирует кнопку слева.
            section.Header.Visible = _categoryFilter == null;
        }
    }

    private bool MatchesSearch(TraitCard card)
    {
        return _search.Length == 0 || card.SearchText.Contains(_search, StringComparison.Ordinal);
    }

    private bool MatchesFilter(TraitCard card)
    {
        if (_filter == TraitFilter.All)
            return true;

        if (!_prototype.TryIndex(card.TraitId, out var trait))
            return false;

        return _filter switch
        {
            TraitFilter.Selected => _selected.Contains(card.TraitId),
            TraitFilter.Grants => trait.Cost < 0,
            TraitFilter.Costs => trait.Cost > 0,
            TraitFilter.Available => _selected.Contains(card.TraitId) || CanSelect(trait, out _),
            _ => true,
        };
    }

    #endregion

    #region Подробности

    private void ShowDetails(ProtoId<TraitPrototype>? id)
    {
        _detailsTrait = id;

        if (id is not { } traitId || !_prototype.TryIndex(traitId, out var trait))
        {
            DetailName.Text = Loc.GetString("duty-traits-details-empty-title");
            DetailCost.Text = string.Empty;
            DetailDescription.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString("duty-traits-details-empty")));
            DetailMeta.SetMessage(new FormattedMessage());
            return;
        }

        DetailName.Text = NameOf(trait);
        DetailCost.Text = trait.Cost switch
        {
            > 0 => Loc.GetString("duty-traits-cost-spend", ("cost", trait.Cost)),
            < 0 => Loc.GetString("duty-traits-cost-grant", ("cost", -trait.Cost)),
            _ => Loc.GetString("duty-traits-cost-free"),
        };

        var description = trait.Description is { } desc ? Loc.GetString(desc) : string.Empty;
        DetailDescription.SetMessage(FormattedMessage.FromMarkupPermissive(description));

        var meta = new FormattedMessage();

        if (_prototype.TryIndex(trait.Category, out var category))
        {
            var limits = new List<string>();
            if (category.MaxTraits is { } maxTraits)
                limits.Add(Loc.GetString("duty-traits-limit-traits", ("max", maxTraits)));
            if (category.MaxPoints is { } maxPoints)
                limits.Add(Loc.GetString("duty-traits-limit-points", ("max", maxPoints)));

            meta.AddText(Loc.GetString("duty-traits-meta-category", ("category", Loc.GetString(category.Name))));
            if (limits.Count > 0)
                meta.AddText($" ({string.Join(", ", limits)})");
            meta.PushNewline();
        }

        // Конфликты: берём в обе стороны, выбранные подсвечиваем.
        var conflicting = _prototype.EnumeratePrototypes<TraitPrototype>()
            .Where(other => other.ID != trait.ID && (trait.Conflicts.Contains(other.ID) || other.Conflicts.Contains(trait.ID)))
            .Where(other => _cards.ContainsKey(other.ID))
            .OrderBy(NameOf, StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        if (conflicting.Count > 0)
        {
            meta.AddText(Loc.GetString("duty-traits-meta-conflicts") + " ");
            for (var i = 0; i < conflicting.Count; i++)
            {
                var other = conflicting[i];
                var taken = _selected.Contains(other.ID);
                if (taken)
                    meta.PushColor(Color.FromHex("#f87171"));
                meta.AddText(NameOf(other));
                if (taken)
                    meta.Pop();
                if (i < conflicting.Count - 1)
                    meta.AddText(", ");
            }

            meta.PushNewline();
        }

        if (trait.SpeciesWhitelist.Count > 0)
            AddLine(meta, Loc.GetString("duty-traits-meta-species-only", ("species", SpeciesNames(trait.SpeciesWhitelist))));
        if (trait.SpeciesBlacklist.Count > 0)
            AddLine(meta, Loc.GetString("duty-traits-meta-species-not", ("species", SpeciesNames(trait.SpeciesBlacklist))));

        if (trait.JobWhitelist.Count > 0)
            AddLine(meta, Loc.GetString("duty-traits-meta-jobs-only", ("jobs", JobNames(trait.JobWhitelist))));
        if (trait.JobBlacklist.Count > 0)
            AddLine(meta, Loc.GetString("duty-traits-meta-jobs-not", ("jobs", JobNames(trait.JobBlacklist))));

        if (_blocked.TryGetValue(trait.ID, out var blockReason))
        {
            meta.PushColor(Color.FromHex("#f87171"));
            meta.AddText(Loc.GetString("duty-traits-meta-blocked", ("reason", blockReason)));
            meta.Pop();
        }
        else if (!_selected.Contains(trait.ID) && !CanSelect(trait, out var reason) && reason != null)
        {
            meta.PushColor(Color.FromHex("#fbbf24"));
            meta.AddText(reason);
            meta.Pop();
        }

        DetailMeta.SetMessage(meta);
    }

    private static void AddLine(FormattedMessage message, string text)
    {
        message.AddText(text);
        message.PushNewline();
    }

    private string JobNames(IEnumerable<ProtoId<JobPrototype>> ids)
    {
        return string.Join(", ", ids.Select(id => _prototype.TryIndex(id, out var job) ? job.LocalizedName : id.Id));
    }

    #endregion
}
// _Duty-end
